/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConnectCarrierRequest,
    ConnectCarrierRequestFromJSON,
    ConnectCarrierRequestToJSON,
} from '../models/ConnectCarrierRequest';
import {
    type ListApiTokens401Response,
    ListApiTokens401ResponseFromJSON,
    ListApiTokens401ResponseToJSON,
} from '../models/ListApiTokens401Response';
import {
    type ListCarrierProductServicePoints200ResponseInner,
    ListCarrierProductServicePoints200ResponseInnerFromJSON,
    ListCarrierProductServicePoints200ResponseInnerToJSON,
} from '../models/ListCarrierProductServicePoints200ResponseInner';
import {
    type ListCarrierProductServicePointsRequest,
    ListCarrierProductServicePointsRequestFromJSON,
    ListCarrierProductServicePointsRequestToJSON,
} from '../models/ListCarrierProductServicePointsRequest';
import {
    type ListCarrierProducts200ResponseInner,
    ListCarrierProducts200ResponseInnerFromJSON,
    ListCarrierProducts200ResponseInnerToJSON,
} from '../models/ListCarrierProducts200ResponseInner';
import {
    type ListCarriers200Response,
    ListCarriers200ResponseFromJSON,
    ListCarriers200ResponseToJSON,
} from '../models/ListCarriers200Response';
import {
    type ListCarriers200ResponseDataInner,
    ListCarriers200ResponseDataInnerFromJSON,
    ListCarriers200ResponseDataInnerToJSON,
} from '../models/ListCarriers200ResponseDataInner';
import {
    type UpdateCarrierRequest,
    UpdateCarrierRequestFromJSON,
    UpdateCarrierRequestToJSON,
} from '../models/UpdateCarrierRequest';

export interface ConnectCarrierOperationRequest {
    orgId: string;
    connectCarrierRequest: ConnectCarrierRequest;
}

export interface DisconnectCarrierRequest {
    orgId: string;
    carrierId: string;
}

export interface GetCarrierRequest {
    orgId: string;
    carrierId: string;
}

export interface ListCarrierProductServicePointsOperationRequest {
    orgId: string;
    carrierId: string;
    productId: string;
    listCarrierProductServicePointsRequest: ListCarrierProductServicePointsRequest;
}

export interface ListCarrierProductsRequest {
    orgId: string;
    carrierId: string;
}

export interface ListCarriersRequest {
    orgId: string;
    page?: number;
    limit?: number;
}

export interface UpdateCarrierOperationRequest {
    orgId: string;
    carrierId: string;
    updateCarrierRequest: UpdateCarrierRequest;
}

/**
 * 
 */
export class CarriersApi extends runtime.BaseAPI {

    /**
     * Creates request options for connectCarrier without sending the request
     */
    async connectCarrierRequestOpts(requestParameters: ConnectCarrierOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling connectCarrier().'
            );
        }

        if (requestParameters['connectCarrierRequest'] == null) {
            throw new runtime.RequiredError(
                'connectCarrierRequest',
                'Required parameter "connectCarrierRequest" was null or undefined when calling connectCarrier().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectCarrierRequestToJSON(requestParameters['connectCarrierRequest']),
        };
    }

    /**
     * Connects a new carrier to the organization with its configuration.
     * Connect carrier
     */
    async connectCarrierRaw(requestParameters: ConnectCarrierOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCarriers200ResponseDataInner>> {
        const requestOptions = await this.connectCarrierRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCarriers200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     * Connects a new carrier to the organization with its configuration.
     * Connect carrier
     */
    async connectCarrier(requestParameters: ConnectCarrierOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCarriers200ResponseDataInner> {
        const response = await this.connectCarrierRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for disconnectCarrier without sending the request
     */
    async disconnectCarrierRequestOpts(requestParameters: DisconnectCarrierRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling disconnectCarrier().'
            );
        }

        if (requestParameters['carrierId'] == null) {
            throw new runtime.RequiredError(
                'carrierId',
                'Required parameter "carrierId" was null or undefined when calling disconnectCarrier().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers/{carrierId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{carrierId}', encodeURIComponent(String(requestParameters['carrierId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Disconnects a carrier from the organization.
     * Disconnect carrier
     */
    async disconnectCarrierRaw(requestParameters: DisconnectCarrierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.disconnectCarrierRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Disconnects a carrier from the organization.
     * Disconnect carrier
     */
    async disconnectCarrier(requestParameters: DisconnectCarrierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.disconnectCarrierRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCarrier without sending the request
     */
    async getCarrierRequestOpts(requestParameters: GetCarrierRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getCarrier().'
            );
        }

        if (requestParameters['carrierId'] == null) {
            throw new runtime.RequiredError(
                'carrierId',
                'Required parameter "carrierId" was null or undefined when calling getCarrier().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers/{carrierId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{carrierId}', encodeURIComponent(String(requestParameters['carrierId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a single connected carrier.
     * Get carrier
     */
    async getCarrierRaw(requestParameters: GetCarrierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCarriers200ResponseDataInner>> {
        const requestOptions = await this.getCarrierRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCarriers200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     * Returns a single connected carrier.
     * Get carrier
     */
    async getCarrier(requestParameters: GetCarrierRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCarriers200ResponseDataInner> {
        const response = await this.getCarrierRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCarrierProductServicePoints without sending the request
     */
    async listCarrierProductServicePointsRequestOpts(requestParameters: ListCarrierProductServicePointsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listCarrierProductServicePoints().'
            );
        }

        if (requestParameters['carrierId'] == null) {
            throw new runtime.RequiredError(
                'carrierId',
                'Required parameter "carrierId" was null or undefined when calling listCarrierProductServicePoints().'
            );
        }

        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling listCarrierProductServicePoints().'
            );
        }

        if (requestParameters['listCarrierProductServicePointsRequest'] == null) {
            throw new runtime.RequiredError(
                'listCarrierProductServicePointsRequest',
                'Required parameter "listCarrierProductServicePointsRequest" was null or undefined when calling listCarrierProductServicePoints().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers/{carrierId}/products/{productId}/service-points`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{carrierId}', encodeURIComponent(String(requestParameters['carrierId'])));
        urlPath = urlPath.replace('{productId}', encodeURIComponent(String(requestParameters['productId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListCarrierProductServicePointsRequestToJSON(requestParameters['listCarrierProductServicePointsRequest']),
        };
    }

    /**
     * Returns pickup service points near a location for a specific carrier product.
     * List product service points
     */
    async listCarrierProductServicePointsRaw(requestParameters: ListCarrierProductServicePointsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListCarrierProductServicePoints200ResponseInner>>> {
        const requestOptions = await this.listCarrierProductServicePointsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListCarrierProductServicePoints200ResponseInnerFromJSON));
    }

    /**
     * Returns pickup service points near a location for a specific carrier product.
     * List product service points
     */
    async listCarrierProductServicePoints(requestParameters: ListCarrierProductServicePointsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListCarrierProductServicePoints200ResponseInner>> {
        const response = await this.listCarrierProductServicePointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCarrierProducts without sending the request
     */
    async listCarrierProductsRequestOpts(requestParameters: ListCarrierProductsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listCarrierProducts().'
            );
        }

        if (requestParameters['carrierId'] == null) {
            throw new runtime.RequiredError(
                'carrierId',
                'Required parameter "carrierId" was null or undefined when calling listCarrierProducts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers/{carrierId}/products`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{carrierId}', encodeURIComponent(String(requestParameters['carrierId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the shipping products available for a connected carrier.
     * List carrier products
     */
    async listCarrierProductsRaw(requestParameters: ListCarrierProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListCarrierProducts200ResponseInner>>> {
        const requestOptions = await this.listCarrierProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListCarrierProducts200ResponseInnerFromJSON));
    }

    /**
     * Returns the shipping products available for a connected carrier.
     * List carrier products
     */
    async listCarrierProducts(requestParameters: ListCarrierProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListCarrierProducts200ResponseInner>> {
        const response = await this.listCarrierProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCarriers without sending the request
     */
    async listCarriersRequestOpts(requestParameters: ListCarriersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listCarriers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of carriers connected to the organization.
     * List carriers
     */
    async listCarriersRaw(requestParameters: ListCarriersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCarriers200Response>> {
        const requestOptions = await this.listCarriersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCarriers200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of carriers connected to the organization.
     * List carriers
     */
    async listCarriers(requestParameters: ListCarriersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCarriers200Response> {
        const response = await this.listCarriersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCarrier without sending the request
     */
    async updateCarrierRequestOpts(requestParameters: UpdateCarrierOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling updateCarrier().'
            );
        }

        if (requestParameters['carrierId'] == null) {
            throw new runtime.RequiredError(
                'carrierId',
                'Required parameter "carrierId" was null or undefined when calling updateCarrier().'
            );
        }

        if (requestParameters['updateCarrierRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCarrierRequest',
                'Required parameter "updateCarrierRequest" was null or undefined when calling updateCarrier().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/carriers/{carrierId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{carrierId}', encodeURIComponent(String(requestParameters['carrierId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCarrierRequestToJSON(requestParameters['updateCarrierRequest']),
        };
    }

    /**
     * Updates a connected carrier\'s configuration or name.
     * Update carrier
     */
    async updateCarrierRaw(requestParameters: UpdateCarrierOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCarriers200ResponseDataInner>> {
        const requestOptions = await this.updateCarrierRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCarriers200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     * Updates a connected carrier\'s configuration or name.
     * Update carrier
     */
    async updateCarrier(requestParameters: UpdateCarrierOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCarriers200ResponseDataInner> {
        const response = await this.updateCarrierRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
