/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BatchSendShipments200Response,
    BatchSendShipments200ResponseFromJSON,
    BatchSendShipments200ResponseToJSON,
} from '../models/BatchSendShipments200Response';
import {
    type BatchSendShipmentsRequest,
    BatchSendShipmentsRequestFromJSON,
    BatchSendShipmentsRequestToJSON,
} from '../models/BatchSendShipmentsRequest';
import {
    type BatchSplitShipment201Response,
    BatchSplitShipment201ResponseFromJSON,
    BatchSplitShipment201ResponseToJSON,
} from '../models/BatchSplitShipment201Response';
import {
    type BatchSplitShipmentRequest,
    BatchSplitShipmentRequestFromJSON,
    BatchSplitShipmentRequestToJSON,
} from '../models/BatchSplitShipmentRequest';
import {
    type CreateShipment201Response,
    CreateShipment201ResponseFromJSON,
    CreateShipment201ResponseToJSON,
} from '../models/CreateShipment201Response';
import {
    type CreateShipmentRequest,
    CreateShipmentRequestFromJSON,
    CreateShipmentRequestToJSON,
} from '../models/CreateShipmentRequest';
import {
    type ListApiTokens401Response,
    ListApiTokens401ResponseFromJSON,
    ListApiTokens401ResponseToJSON,
} from '../models/ListApiTokens401Response';
import {
    type ListShipments200Response,
    ListShipments200ResponseFromJSON,
    ListShipments200ResponseToJSON,
} from '../models/ListShipments200Response';
import {
    type RevokeApiToken200Response,
    RevokeApiToken200ResponseFromJSON,
    RevokeApiToken200ResponseToJSON,
} from '../models/RevokeApiToken200Response';
import {
    type SendShipment422Response,
    SendShipment422ResponseFromJSON,
    SendShipment422ResponseToJSON,
} from '../models/SendShipment422Response';
import {
    type SplitShipment201Response,
    SplitShipment201ResponseFromJSON,
    SplitShipment201ResponseToJSON,
} from '../models/SplitShipment201Response';
import {
    type SplitShipmentParcel200Response,
    SplitShipmentParcel200ResponseFromJSON,
    SplitShipmentParcel200ResponseToJSON,
} from '../models/SplitShipmentParcel200Response';
import {
    type SplitShipmentParcelRequest,
    SplitShipmentParcelRequestFromJSON,
    SplitShipmentParcelRequestToJSON,
} from '../models/SplitShipmentParcelRequest';
import {
    type SplitShipmentRequest,
    SplitShipmentRequestFromJSON,
    SplitShipmentRequestToJSON,
} from '../models/SplitShipmentRequest';
import {
    type TrackShipment200Response,
    TrackShipment200ResponseFromJSON,
    TrackShipment200ResponseToJSON,
} from '../models/TrackShipment200Response';
import {
    type UpdateShipmentRequest,
    UpdateShipmentRequestFromJSON,
    UpdateShipmentRequestToJSON,
} from '../models/UpdateShipmentRequest';

export interface BatchSendShipmentsOperationRequest {
    orgId: string;
    batchSendShipmentsRequest: BatchSendShipmentsRequest;
}

export interface BatchSplitShipmentOperationRequest {
    orgId: string;
    shipmentId: string;
    batchSplitShipmentRequest: BatchSplitShipmentRequest;
}

export interface CreateReturnShipmentRequest {
    orgId: string;
    shipmentId: string;
}

export interface CreateShipmentOperationRequest {
    orgId: string;
    createShipmentRequest: CreateShipmentRequest;
}

export interface DeleteShipmentRequest {
    orgId: string;
    shipmentId: string;
}

export interface GetShipmentRequest {
    orgId: string;
    shipmentId: string;
}

export interface GetShipmentDocumentContentRequest {
    orgId: string;
    shipmentId: string;
    documentId: string;
    disposition?: GetShipmentDocumentContentDispositionEnum;
    filename?: string;
}

export interface ListShipmentsRequest {
    orgId: string;
    page?: number;
    limit?: number;
    brandId?: string;
}

export interface SendShipmentRequest {
    orgId: string;
    shipmentId: string;
}

export interface SplitShipmentOperationRequest {
    orgId: string;
    shipmentId: string;
    splitShipmentRequest: SplitShipmentRequest;
}

export interface SplitShipmentParcelOperationRequest {
    orgId: string;
    shipmentId: string;
    splitShipmentParcelRequest: SplitShipmentParcelRequest;
}

export interface TrackShipmentRequest {
    orgId: string;
    shipmentId: string;
}

export interface UpdateShipmentOperationRequest {
    orgId: string;
    shipmentId: string;
    updateShipmentRequest: UpdateShipmentRequest;
}

/**
 * 
 */
export class ShipmentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for batchSendShipments without sending the request
     */
    async batchSendShipmentsRequestOpts(requestParameters: BatchSendShipmentsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling batchSendShipments().'
            );
        }

        if (requestParameters['batchSendShipmentsRequest'] == null) {
            throw new runtime.RequiredError(
                'batchSendShipmentsRequest',
                'Required parameter "batchSendShipmentsRequest" was null or undefined when calling batchSendShipments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/batch-send`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchSendShipmentsRequestToJSON(requestParameters['batchSendShipmentsRequest']),
        };
    }

    /**
     * Book multiple pending/error shipments with their carriers in one request. Each shipment is processed independently and reported in `results`; a failure on one shipment never aborts the others. Use it to send every shipment on an order at once.
     * Batch send shipments
     */
    async batchSendShipmentsRaw(requestParameters: BatchSendShipmentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchSendShipments200Response>> {
        const requestOptions = await this.batchSendShipmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchSendShipments200ResponseFromJSON(jsonValue));
    }

    /**
     * Book multiple pending/error shipments with their carriers in one request. Each shipment is processed independently and reported in `results`; a failure on one shipment never aborts the others. Use it to send every shipment on an order at once.
     * Batch send shipments
     */
    async batchSendShipments(requestParameters: BatchSendShipmentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchSendShipments200Response> {
        const response = await this.batchSendShipmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for batchSplitShipment without sending the request
     */
    async batchSplitShipmentRequestOpts(requestParameters: BatchSplitShipmentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling batchSplitShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling batchSplitShipment().'
            );
        }

        if (requestParameters['batchSplitShipmentRequest'] == null) {
            throw new runtime.RequiredError(
                'batchSplitShipmentRequest',
                'Required parameter "batchSplitShipmentRequest" was null or undefined when calling batchSplitShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/batch-split-shipment`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchSplitShipmentRequestToJSON(requestParameters['batchSplitShipmentRequest']),
        };
    }

    /**
     * Split a parcel into multiple new shipments with per-line quantities in a single atomic operation. Only draft or pending shipments can be split.
     * Batch split shipment
     */
    async batchSplitShipmentRaw(requestParameters: BatchSplitShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchSplitShipment201Response>> {
        const requestOptions = await this.batchSplitShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchSplitShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Split a parcel into multiple new shipments with per-line quantities in a single atomic operation. Only draft or pending shipments can be split.
     * Batch split shipment
     */
    async batchSplitShipment(requestParameters: BatchSplitShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchSplitShipment201Response> {
        const response = await this.batchSplitShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createReturnShipment without sending the request
     */
    async createReturnShipmentRequestOpts(requestParameters: CreateReturnShipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createReturnShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling createReturnShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/create-return`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create and auto-send a return shipment from a dispatched outbound shipment with swapped sender/receiver. Requires a configured return shipping rule.
     * Create return shipment
     */
    async createReturnShipmentRaw(requestParameters: CreateReturnShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateShipment201Response>> {
        const requestOptions = await this.createReturnShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Create and auto-send a return shipment from a dispatched outbound shipment with swapped sender/receiver. Requires a configured return shipping rule.
     * Create return shipment
     */
    async createReturnShipment(requestParameters: CreateReturnShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateShipment201Response> {
        const response = await this.createReturnShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createShipment without sending the request
     */
    async createShipmentRequestOpts(requestParameters: CreateShipmentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createShipment().'
            );
        }

        if (requestParameters['createShipmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createShipmentRequest',
                'Required parameter "createShipmentRequest" was null or undefined when calling createShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateShipmentRequestToJSON(requestParameters['createShipmentRequest']),
        };
    }

    /**
     * Create a new shipment for an organization. When orderId is provided, parties and parcels are derived from the order.
     * Create shipment
     */
    async createShipmentRaw(requestParameters: CreateShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateShipment201Response>> {
        const requestOptions = await this.createShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new shipment for an organization. When orderId is provided, parties and parcels are derived from the order.
     * Create shipment
     */
    async createShipment(requestParameters: CreateShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateShipment201Response> {
        const response = await this.createShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteShipment without sending the request
     */
    async deleteShipmentRequestOpts(requestParameters: DeleteShipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling deleteShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling deleteShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a shipment. Only shipments in pending status can be deleted.
     * Delete shipment
     */
    async deleteShipmentRaw(requestParameters: DeleteShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RevokeApiToken200Response>> {
        const requestOptions = await this.deleteShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RevokeApiToken200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a shipment. Only shipments in pending status can be deleted.
     * Delete shipment
     */
    async deleteShipment(requestParameters: DeleteShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RevokeApiToken200Response> {
        const response = await this.deleteShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getShipment without sending the request
     */
    async getShipmentRequestOpts(requestParameters: GetShipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling getShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a single shipment by its ID, including parcels, parties, documents and activity.
     * Get shipment
     */
    async getShipmentRaw(requestParameters: GetShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateShipment201Response>> {
        const requestOptions = await this.getShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a single shipment by its ID, including parcels, parties, documents and activity.
     * Get shipment
     */
    async getShipment(requestParameters: GetShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateShipment201Response> {
        const response = await this.getShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getShipmentDocumentContent without sending the request
     */
    async getShipmentDocumentContentRequestOpts(requestParameters: GetShipmentDocumentContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getShipmentDocumentContent().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling getShipmentDocumentContent().'
            );
        }

        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling getShipmentDocumentContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['disposition'] != null) {
            queryParameters['disposition'] = requestParameters['disposition'];
        }

        if (requestParameters['filename'] != null) {
            queryParameters['filename'] = requestParameters['filename'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/documents/{documentId}/content`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));
        urlPath = urlPath.replace('{documentId}', encodeURIComponent(String(requestParameters['documentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Streams a shipment document or label file from storage.
     * Download shipment document
     */
    async getShipmentDocumentContentRaw(requestParameters: GetShipmentDocumentContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getShipmentDocumentContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Streams a shipment document or label file from storage.
     * Download shipment document
     */
    async getShipmentDocumentContent(requestParameters: GetShipmentDocumentContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getShipmentDocumentContentRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listShipments without sending the request
     */
    async listShipmentsRequestOpts(requestParameters: ListShipmentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listShipments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['brandId'] != null) {
            queryParameters['brandId'] = requestParameters['brandId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all shipments for an organization, paginated and ordered by newest first.
     * List shipments
     */
    async listShipmentsRaw(requestParameters: ListShipmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListShipments200Response>> {
        const requestOptions = await this.listShipmentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListShipments200ResponseFromJSON(jsonValue));
    }

    /**
     * List all shipments for an organization, paginated and ordered by newest first.
     * List shipments
     */
    async listShipments(requestParameters: ListShipmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListShipments200Response> {
        const response = await this.listShipmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendShipment without sending the request
     */
    async sendShipmentRequestOpts(requestParameters: SendShipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling sendShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling sendShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/send`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Book a pending or error shipment with the carrier, generating labels and tracking. Returns 422 with carrier errors if booking fails.
     * Send shipment
     */
    async sendShipmentRaw(requestParameters: SendShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateShipment201Response>> {
        const requestOptions = await this.sendShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Book a pending or error shipment with the carrier, generating labels and tracking. Returns 422 with carrier errors if booking fails.
     * Send shipment
     */
    async sendShipment(requestParameters: SendShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateShipment201Response> {
        const response = await this.sendShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for splitShipment without sending the request
     */
    async splitShipmentRequestOpts(requestParameters: SplitShipmentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling splitShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling splitShipment().'
            );
        }

        if (requestParameters['splitShipmentRequest'] == null) {
            throw new runtime.RequiredError(
                'splitShipmentRequest',
                'Required parameter "splitShipmentRequest" was null or undefined when calling splitShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/split-shipment`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SplitShipmentRequestToJSON(requestParameters['splitShipmentRequest']),
        };
    }

    /**
     * Move order lines from a parcel into a new shipment. Only draft or pending shipments can be split.
     * Split shipment
     */
    async splitShipmentRaw(requestParameters: SplitShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SplitShipment201Response>> {
        const requestOptions = await this.splitShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SplitShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Move order lines from a parcel into a new shipment. Only draft or pending shipments can be split.
     * Split shipment
     */
    async splitShipment(requestParameters: SplitShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SplitShipment201Response> {
        const response = await this.splitShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for splitShipmentParcel without sending the request
     */
    async splitShipmentParcelRequestOpts(requestParameters: SplitShipmentParcelOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling splitShipmentParcel().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling splitShipmentParcel().'
            );
        }

        if (requestParameters['splitShipmentParcelRequest'] == null) {
            throw new runtime.RequiredError(
                'splitShipmentParcelRequest',
                'Required parameter "splitShipmentParcelRequest" was null or undefined when calling splitShipmentParcel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/split-parcel`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SplitShipmentParcelRequestToJSON(requestParameters['splitShipmentParcelRequest']),
        };
    }

    /**
     * Redistribute order lines across parcels within a shipment, moving lines between parcels and creating new ones. Only draft, pending or error shipments can be modified.
     * Split parcels
     */
    async splitShipmentParcelRaw(requestParameters: SplitShipmentParcelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SplitShipmentParcel200Response>> {
        const requestOptions = await this.splitShipmentParcelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SplitShipmentParcel200ResponseFromJSON(jsonValue));
    }

    /**
     * Redistribute order lines across parcels within a shipment, moving lines between parcels and creating new ones. Only draft, pending or error shipments can be modified.
     * Split parcels
     */
    async splitShipmentParcel(requestParameters: SplitShipmentParcelOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SplitShipmentParcel200Response> {
        const response = await this.splitShipmentParcelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for trackShipment without sending the request
     */
    async trackShipmentRequestOpts(requestParameters: TrackShipmentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling trackShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling trackShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}/tracking`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve the tracking timeline for a shipment, including current status and all carrier events.
     * Get shipment tracking
     */
    async trackShipmentRaw(requestParameters: TrackShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TrackShipment200Response>> {
        const requestOptions = await this.trackShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrackShipment200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve the tracking timeline for a shipment, including current status and all carrier events.
     * Get shipment tracking
     */
    async trackShipment(requestParameters: TrackShipmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TrackShipment200Response> {
        const response = await this.trackShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateShipment without sending the request
     */
    async updateShipmentRequestOpts(requestParameters: UpdateShipmentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling updateShipment().'
            );
        }

        if (requestParameters['shipmentId'] == null) {
            throw new runtime.RequiredError(
                'shipmentId',
                'Required parameter "shipmentId" was null or undefined when calling updateShipment().'
            );
        }

        if (requestParameters['updateShipmentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateShipmentRequest',
                'Required parameter "updateShipmentRequest" was null or undefined when calling updateShipment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/shipments/{shipmentId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{shipmentId}', encodeURIComponent(String(requestParameters['shipmentId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateShipmentRequestToJSON(requestParameters['updateShipmentRequest']),
        };
    }

    /**
     * Update an existing shipment. Only draft, pending or error shipments can be updated; an applied shipping rule overrides carrier settings and sender party.
     * Update shipment
     */
    async updateShipmentRaw(requestParameters: UpdateShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateShipment201Response>> {
        const requestOptions = await this.updateShipmentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateShipment201ResponseFromJSON(jsonValue));
    }

    /**
     * Update an existing shipment. Only draft, pending or error shipments can be updated; an applied shipping rule overrides carrier settings and sender party.
     * Update shipment
     */
    async updateShipment(requestParameters: UpdateShipmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateShipment201Response> {
        const response = await this.updateShipmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetShipmentDocumentContentDispositionEnum = {
    Inline: 'inline',
    Attachment: 'attachment'
} as const;
export type GetShipmentDocumentContentDispositionEnum = typeof GetShipmentDocumentContentDispositionEnum[keyof typeof GetShipmentDocumentContentDispositionEnum];
