/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateApiToken201Response,
    CreateApiToken201ResponseFromJSON,
    CreateApiToken201ResponseToJSON,
} from '../models/CreateApiToken201Response';
import {
    type CreateApiTokenRequest,
    CreateApiTokenRequestFromJSON,
    CreateApiTokenRequestToJSON,
} from '../models/CreateApiTokenRequest';
import {
    type ListApiTokens200Response,
    ListApiTokens200ResponseFromJSON,
    ListApiTokens200ResponseToJSON,
} from '../models/ListApiTokens200Response';
import {
    type ListApiTokens200ResponseDataInner,
    ListApiTokens200ResponseDataInnerFromJSON,
    ListApiTokens200ResponseDataInnerToJSON,
} from '../models/ListApiTokens200ResponseDataInner';
import {
    type ListApiTokens401Response,
    ListApiTokens401ResponseFromJSON,
    ListApiTokens401ResponseToJSON,
} from '../models/ListApiTokens401Response';
import {
    type RevokeApiToken200Response,
    RevokeApiToken200ResponseFromJSON,
    RevokeApiToken200ResponseToJSON,
} from '../models/RevokeApiToken200Response';
import {
    type UpdateApiTokenRequest,
    UpdateApiTokenRequestFromJSON,
    UpdateApiTokenRequestToJSON,
} from '../models/UpdateApiTokenRequest';
import {
    type VerifyApiToken200Response,
    VerifyApiToken200ResponseFromJSON,
    VerifyApiToken200ResponseToJSON,
} from '../models/VerifyApiToken200Response';
import {
    type VerifyApiTokenRequest,
    VerifyApiTokenRequestFromJSON,
    VerifyApiTokenRequestToJSON,
} from '../models/VerifyApiTokenRequest';

export interface CreateApiTokenOperationRequest {
    orgId: string;
    createApiTokenRequest: CreateApiTokenRequest;
}

export interface GetApiTokenRequest {
    orgId: string;
    tokenId: string;
}

export interface ListApiTokensRequest {
    orgId: string;
    page?: number;
    limit?: number;
}

export interface RevokeApiTokenRequest {
    orgId: string;
    tokenId: string;
}

export interface UpdateApiTokenOperationRequest {
    orgId: string;
    tokenId: string;
    updateApiTokenRequest: UpdateApiTokenRequest;
}

export interface VerifyApiTokenOperationRequest {
    verifyApiTokenRequest: VerifyApiTokenRequest;
}

/**
 * 
 */
export class TokensApi extends runtime.BaseAPI {

    /**
     * Creates request options for createApiToken without sending the request
     */
    async createApiTokenRequestOpts(requestParameters: CreateApiTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createApiToken().'
            );
        }

        if (requestParameters['createApiTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'createApiTokenRequest',
                'Required parameter "createApiTokenRequest" was null or undefined when calling createApiToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/api-tokens`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateApiTokenRequestToJSON(requestParameters['createApiTokenRequest']),
        };
    }

    /**
     * Creates a new API token for the specified organization. The full token is only shown once.
     * Create API keys
     */
    async createApiTokenRaw(requestParameters: CreateApiTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateApiToken201Response>> {
        const requestOptions = await this.createApiTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateApiToken201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new API token for the specified organization. The full token is only shown once.
     * Create API keys
     */
    async createApiToken(requestParameters: CreateApiTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateApiToken201Response> {
        const response = await this.createApiTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiToken without sending the request
     */
    async getApiTokenRequestOpts(requestParameters: GetApiTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling getApiToken().'
            );
        }

        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling getApiToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/api-tokens/{tokenId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{tokenId}', encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns metadata for a specific API token. The token secret is never returned.
     * Get API keys
     */
    async getApiTokenRaw(requestParameters: GetApiTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApiTokens200ResponseDataInner>> {
        const requestOptions = await this.getApiTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApiTokens200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     * Returns metadata for a specific API token. The token secret is never returned.
     * Get API keys
     */
    async getApiToken(requestParameters: GetApiTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApiTokens200ResponseDataInner> {
        const response = await this.getApiTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApiTokens without sending the request
     */
    async listApiTokensRequestOpts(requestParameters: ListApiTokensRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listApiTokens().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/api-tokens`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a paginated list of API tokens belonging to the specified organization.
     * List API keys
     */
    async listApiTokensRaw(requestParameters: ListApiTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApiTokens200Response>> {
        const requestOptions = await this.listApiTokensRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApiTokens200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of API tokens belonging to the specified organization.
     * List API keys
     */
    async listApiTokens(requestParameters: ListApiTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApiTokens200Response> {
        const response = await this.listApiTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeApiToken without sending the request
     */
    async revokeApiTokenRequestOpts(requestParameters: RevokeApiTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling revokeApiToken().'
            );
        }

        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling revokeApiToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/api-tokens/{tokenId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{tokenId}', encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revokes and deletes an API token.
     * Revoke API keys
     */
    async revokeApiTokenRaw(requestParameters: RevokeApiTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RevokeApiToken200Response>> {
        const requestOptions = await this.revokeApiTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RevokeApiToken200ResponseFromJSON(jsonValue));
    }

    /**
     * Revokes and deletes an API token.
     * Revoke API keys
     */
    async revokeApiToken(requestParameters: RevokeApiTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RevokeApiToken200Response> {
        const response = await this.revokeApiTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiToken without sending the request
     */
    async updateApiTokenRequestOpts(requestParameters: UpdateApiTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling updateApiToken().'
            );
        }

        if (requestParameters['tokenId'] == null) {
            throw new runtime.RequiredError(
                'tokenId',
                'Required parameter "tokenId" was null or undefined when calling updateApiToken().'
            );
        }

        if (requestParameters['updateApiTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'updateApiTokenRequest',
                'Required parameter "updateApiTokenRequest" was null or undefined when calling updateApiToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{orgId}/api-tokens/{tokenId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));
        urlPath = urlPath.replace('{tokenId}', encodeURIComponent(String(requestParameters['tokenId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateApiTokenRequestToJSON(requestParameters['updateApiTokenRequest']),
        };
    }

    /**
     * Updates the name of an API token.
     * Update API keys
     */
    async updateApiTokenRaw(requestParameters: UpdateApiTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListApiTokens200ResponseDataInner>> {
        const requestOptions = await this.updateApiTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListApiTokens200ResponseDataInnerFromJSON(jsonValue));
    }

    /**
     * Updates the name of an API token.
     * Update API keys
     */
    async updateApiToken(requestParameters: UpdateApiTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListApiTokens200ResponseDataInner> {
        const response = await this.updateApiTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyApiToken without sending the request
     */
    async verifyApiTokenRequestOpts(requestParameters: VerifyApiTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyApiTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyApiTokenRequest',
                'Required parameter "verifyApiTokenRequest" was null or undefined when calling verifyApiToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-tokens/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyApiTokenRequestToJSON(requestParameters['verifyApiTokenRequest']),
        };
    }

    /**
     * Verifies whether an API token is valid and returns its metadata.
     * Verify API keys
     */
    async verifyApiTokenRaw(requestParameters: VerifyApiTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyApiToken200Response>> {
        const requestOptions = await this.verifyApiTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyApiToken200ResponseFromJSON(jsonValue));
    }

    /**
     * Verifies whether an API token is valid and returns its metadata.
     * Verify API keys
     */
    async verifyApiToken(requestParameters: VerifyApiTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyApiToken200Response> {
        const response = await this.verifyApiTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
