/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchSendShipments200ResponseSummary } from './BatchSendShipments200ResponseSummary';
import {
    BatchSendShipments200ResponseSummaryFromJSON,
    BatchSendShipments200ResponseSummaryFromJSONTyped,
    BatchSendShipments200ResponseSummaryToJSON,
    BatchSendShipments200ResponseSummaryToJSONTyped,
} from './BatchSendShipments200ResponseSummary';
import type { BatchSendShipments200ResponseResultsInner } from './BatchSendShipments200ResponseResultsInner';
import {
    BatchSendShipments200ResponseResultsInnerFromJSON,
    BatchSendShipments200ResponseResultsInnerFromJSONTyped,
    BatchSendShipments200ResponseResultsInnerToJSON,
    BatchSendShipments200ResponseResultsInnerToJSONTyped,
} from './BatchSendShipments200ResponseResultsInner';

/**
 * 
 * @export
 * @interface BatchSendShipments200Response
 */
export interface BatchSendShipments200Response {
    /**
     * Per-shipment outcome (one entry per unique requested shipment id).
     * @type {Array<BatchSendShipments200ResponseResultsInner>}
     * @memberof BatchSendShipments200Response
     */
    results: Array<BatchSendShipments200ResponseResultsInner>;
    /**
     * 
     * @type {BatchSendShipments200ResponseSummary}
     * @memberof BatchSendShipments200Response
     */
    summary: BatchSendShipments200ResponseSummary;
}

/**
 * Check if a given object implements the BatchSendShipments200Response interface.
 */
export function instanceOfBatchSendShipments200Response(value: object): value is BatchSendShipments200Response {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function BatchSendShipments200ResponseFromJSON(json: any): BatchSendShipments200Response {
    return BatchSendShipments200ResponseFromJSONTyped(json, false);
}

export function BatchSendShipments200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchSendShipments200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(BatchSendShipments200ResponseResultsInnerFromJSON)),
        'summary': BatchSendShipments200ResponseSummaryFromJSON(json['summary']),
    };
}

export function BatchSendShipments200ResponseToJSON(json: any): BatchSendShipments200Response {
    return BatchSendShipments200ResponseToJSONTyped(json, false);
}

export function BatchSendShipments200ResponseToJSONTyped(value?: BatchSendShipments200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(BatchSendShipments200ResponseResultsInnerToJSON)),
        'summary': BatchSendShipments200ResponseSummaryToJSON(value['summary']),
    };
}

