/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateShipment201Response } from './CreateShipment201Response';
import {
    CreateShipment201ResponseFromJSON,
    CreateShipment201ResponseFromJSONTyped,
    CreateShipment201ResponseToJSON,
    CreateShipment201ResponseToJSONTyped,
} from './CreateShipment201Response';

/**
 * 
 * @export
 * @interface BatchSplitShipment201Response
 */
export interface BatchSplitShipment201Response {
    /**
     * 
     * @type {CreateShipment201Response}
     * @memberof BatchSplitShipment201Response
     */
    originalShipment: CreateShipment201Response;
    /**
     * Newly created shipments resulting from the split.
     * @type {Array<CreateShipment201Response>}
     * @memberof BatchSplitShipment201Response
     */
    newShipments: Array<CreateShipment201Response>;
}

/**
 * Check if a given object implements the BatchSplitShipment201Response interface.
 */
export function instanceOfBatchSplitShipment201Response(value: object): value is BatchSplitShipment201Response {
    if (!('originalShipment' in value) || value['originalShipment'] === undefined) return false;
    if (!('newShipments' in value) || value['newShipments'] === undefined) return false;
    return true;
}

export function BatchSplitShipment201ResponseFromJSON(json: any): BatchSplitShipment201Response {
    return BatchSplitShipment201ResponseFromJSONTyped(json, false);
}

export function BatchSplitShipment201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchSplitShipment201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'originalShipment': CreateShipment201ResponseFromJSON(json['originalShipment']),
        'newShipments': ((json['newShipments'] as Array<any>).map(CreateShipment201ResponseFromJSON)),
    };
}

export function BatchSplitShipment201ResponseToJSON(json: any): BatchSplitShipment201Response {
    return BatchSplitShipment201ResponseToJSONTyped(json, false);
}

export function BatchSplitShipment201ResponseToJSONTyped(value?: BatchSplitShipment201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'originalShipment': CreateShipment201ResponseToJSON(value['originalShipment']),
        'newShipments': ((value['newShipments'] as Array<any>).map(CreateShipment201ResponseToJSON)),
    };
}

