/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrder201ResponseOrderLinesInner
 */
export interface CreateOrder201ResponseOrderLinesInner {
    /**
     * Stock keeping unit identifier.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    sku?: string | null;
    /**
     * Product name.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    name: string;
    /**
     * Quantity ordered.
     * @type {number}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    quantity: number;
    /**
     * Price per unit.
     * @type {number}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    unitPrice?: number | null;
    /**
     * Total price for the line.
     * @type {number}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    totalPrice?: number | null;
    /**
     * ISO 4217 currency code.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    currency?: string | null;
    /**
     * Item weight in the given unit.
     * @type {number}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    weight?: number | null;
    /**
     * Unit of the weight value.
     * @type {CreateOrder201ResponseOrderLinesInnerWeightUnitEnum}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    weightUnit?: CreateOrder201ResponseOrderLinesInnerWeightUnitEnum | null;
    /**
     * Platform variant identifier.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    variantId?: string | null;
    /**
     * Platform product identifier.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    productId?: string | null;
    /**
     * Product image URL.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    imageUrl?: string | null;
    /**
     * Harmonized System customs code (6-13 digits).
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    hsCode?: string | null;
    /**
     * ISO 3166-1 alpha-2 country of origin.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    countryOfOrigin?: string | null;
    /**
     * ISO 3166-2 province of origin.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    provinceOfOrigin?: string | null;
    /**
     * Item barcode (EAN/UPC).
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    barcode?: string | null;
    /**
     * Whether the item requires shipping.
     * @type {boolean}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    requiresShipping?: boolean | null;
    /**
     * Whether the item is taxable.
     * @type {boolean}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    taxable?: boolean | null;
    /**
     * Whether the item is a gift card.
     * @type {boolean}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    giftCard?: boolean | null;
    /**
     * Vendor or brand name.
     * @type {string}
     * @memberof CreateOrder201ResponseOrderLinesInner
     */
    vendor?: string | null;
}


/**
 * @export
 */
export const CreateOrder201ResponseOrderLinesInnerWeightUnitEnum = {
    Kg: 'kg',
    G: 'g',
    Lb: 'lb',
    Oz: 'oz'
} as const;
export type CreateOrder201ResponseOrderLinesInnerWeightUnitEnum = typeof CreateOrder201ResponseOrderLinesInnerWeightUnitEnum[keyof typeof CreateOrder201ResponseOrderLinesInnerWeightUnitEnum];


/**
 * Check if a given object implements the CreateOrder201ResponseOrderLinesInner interface.
 */
export function instanceOfCreateOrder201ResponseOrderLinesInner(value: object): value is CreateOrder201ResponseOrderLinesInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CreateOrder201ResponseOrderLinesInnerFromJSON(json: any): CreateOrder201ResponseOrderLinesInner {
    return CreateOrder201ResponseOrderLinesInnerFromJSONTyped(json, false);
}

export function CreateOrder201ResponseOrderLinesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrder201ResponseOrderLinesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'sku': json['sku'] === undefined ? undefined : json['sku'] === null ? null : json['sku'],
        'name': json['name'],
        'quantity': json['quantity'],
        'unitPrice': json['unitPrice'] === undefined ? undefined : json['unitPrice'] === null ? null : json['unitPrice'],
        'totalPrice': json['totalPrice'] === undefined ? undefined : json['totalPrice'] === null ? null : json['totalPrice'],
        'currency': json['currency'] === undefined ? undefined : json['currency'] === null ? null : json['currency'],
        'weight': json['weight'] === undefined ? undefined : json['weight'] === null ? null : json['weight'],
        'weightUnit': json['weightUnit'] === undefined ? undefined : json['weightUnit'] === null ? null : json['weightUnit'],
        'variantId': json['variantId'] === undefined ? undefined : json['variantId'] === null ? null : json['variantId'],
        'productId': json['productId'] === undefined ? undefined : json['productId'] === null ? null : json['productId'],
        'imageUrl': json['imageUrl'] === undefined ? undefined : json['imageUrl'] === null ? null : json['imageUrl'],
        'hsCode': json['hsCode'] === undefined ? undefined : json['hsCode'] === null ? null : json['hsCode'],
        'countryOfOrigin': json['countryOfOrigin'] === undefined ? undefined : json['countryOfOrigin'] === null ? null : json['countryOfOrigin'],
        'provinceOfOrigin': json['provinceOfOrigin'] === undefined ? undefined : json['provinceOfOrigin'] === null ? null : json['provinceOfOrigin'],
        'barcode': json['barcode'] === undefined ? undefined : json['barcode'] === null ? null : json['barcode'],
        'requiresShipping': json['requiresShipping'] === undefined ? undefined : json['requiresShipping'] === null ? null : json['requiresShipping'],
        'taxable': json['taxable'] === undefined ? undefined : json['taxable'] === null ? null : json['taxable'],
        'giftCard': json['giftCard'] === undefined ? undefined : json['giftCard'] === null ? null : json['giftCard'],
        'vendor': json['vendor'] === undefined ? undefined : json['vendor'] === null ? null : json['vendor'],
    };
}

export function CreateOrder201ResponseOrderLinesInnerToJSON(json: any): CreateOrder201ResponseOrderLinesInner {
    return CreateOrder201ResponseOrderLinesInnerToJSONTyped(json, false);
}

export function CreateOrder201ResponseOrderLinesInnerToJSONTyped(value?: CreateOrder201ResponseOrderLinesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sku': value['sku'],
        'name': value['name'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
        'totalPrice': value['totalPrice'],
        'currency': value['currency'],
        'weight': value['weight'],
        'weightUnit': value['weightUnit'],
        'variantId': value['variantId'],
        'productId': value['productId'],
        'imageUrl': value['imageUrl'],
        'hsCode': value['hsCode'],
        'countryOfOrigin': value['countryOfOrigin'],
        'provinceOfOrigin': value['provinceOfOrigin'],
        'barcode': value['barcode'],
        'requiresShipping': value['requiresShipping'],
        'taxable': value['taxable'],
        'giftCard': value['giftCard'],
        'vendor': value['vendor'],
    };
}

