/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateShipment201ResponsePartiesInnerAttributesInner } from './CreateShipment201ResponsePartiesInnerAttributesInner';
import {
    CreateShipment201ResponsePartiesInnerAttributesInnerFromJSON,
    CreateShipment201ResponsePartiesInnerAttributesInnerFromJSONTyped,
    CreateShipment201ResponsePartiesInnerAttributesInnerToJSON,
    CreateShipment201ResponsePartiesInnerAttributesInnerToJSONTyped,
} from './CreateShipment201ResponsePartiesInnerAttributesInner';

/**
 * 
 * @export
 * @interface CreateShipment201ResponsePartiesInner
 */
export interface CreateShipment201ResponsePartiesInner {
    /**
     * Role of the party in the shipment.
     * @type {CreateShipment201ResponsePartiesInnerTypeEnum}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    type: CreateShipment201ResponsePartiesInnerTypeEnum;
    /**
     * Full name or company name of the party.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    name: string;
    /**
     * Attention contact at the party.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    attention?: string | null;
    /**
     * Primary street address line.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    address1: string;
    /**
     * Secondary address line.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    address2?: string | null;
    /**
     * Postal code of the party address.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    postalCode: string;
    /**
     * City of the party address.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    city: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    countryCode: string;
    /**
     * Email address of the party.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    email?: string | null;
    /**
     * Phone number of the party in E.164 format.
     * @type {string}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    phone?: string | null;
    /**
     * Additional carrier-specific attributes for the party.
     * @type {Array<CreateShipment201ResponsePartiesInnerAttributesInner>}
     * @memberof CreateShipment201ResponsePartiesInner
     */
    attributes: Array<CreateShipment201ResponsePartiesInnerAttributesInner>;
}


/**
 * @export
 */
export const CreateShipment201ResponsePartiesInnerTypeEnum = {
    Sender: 'sender',
    Receiver: 'receiver',
    Pickup: 'pickup',
    Billing: 'billing',
    FreightPayer: 'freight_payer',
    ServicePoint: 'service_point',
    Return: 'return'
} as const;
export type CreateShipment201ResponsePartiesInnerTypeEnum = typeof CreateShipment201ResponsePartiesInnerTypeEnum[keyof typeof CreateShipment201ResponsePartiesInnerTypeEnum];


/**
 * Check if a given object implements the CreateShipment201ResponsePartiesInner interface.
 */
export function instanceOfCreateShipment201ResponsePartiesInner(value: object): value is CreateShipment201ResponsePartiesInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address1' in value) || value['address1'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    return true;
}

export function CreateShipment201ResponsePartiesInnerFromJSON(json: any): CreateShipment201ResponsePartiesInner {
    return CreateShipment201ResponsePartiesInnerFromJSONTyped(json, false);
}

export function CreateShipment201ResponsePartiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShipment201ResponsePartiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'name': json['name'],
        'attention': json['attention'] === undefined ? undefined : json['attention'] === null ? null : json['attention'],
        'address1': json['address1'],
        'address2': json['address2'] === undefined ? undefined : json['address2'] === null ? null : json['address2'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'countryCode': json['countryCode'],
        'email': json['email'] === undefined ? undefined : json['email'] === null ? null : json['email'],
        'phone': json['phone'] === undefined ? undefined : json['phone'] === null ? null : json['phone'],
        'attributes': ((json['attributes'] as Array<any>).map(CreateShipment201ResponsePartiesInnerAttributesInnerFromJSON)),
    };
}

export function CreateShipment201ResponsePartiesInnerToJSON(json: any): CreateShipment201ResponsePartiesInner {
    return CreateShipment201ResponsePartiesInnerToJSONTyped(json, false);
}

export function CreateShipment201ResponsePartiesInnerToJSONTyped(value?: CreateShipment201ResponsePartiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'attention': value['attention'],
        'address1': value['address1'],
        'address2': value['address2'],
        'postalCode': value['postalCode'],
        'city': value['city'],
        'countryCode': value['countryCode'],
        'email': value['email'],
        'phone': value['phone'],
        'attributes': ((value['attributes'] as Array<any>).map(CreateShipment201ResponsePartiesInnerAttributesInnerToJSON)),
    };
}

