/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShippingQuote200ResponseRatesInner
 */
export interface CreateShippingQuote200ResponseRatesInner {
    /**
     * Display name of the shipping option
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    serviceName: string;
    /**
     * Unique identifier for this shipping option
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    serviceCode: string;
    /**
     * Total shipping price in cents as string
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    totalPrice: string;
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    currency: string;
    /**
     * Optional description
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    description?: string;
    /**
     * Minimum delivery date (ISO 8601)
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    minDeliveryDate?: string;
    /**
     * Maximum delivery date (ISO 8601)
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    maxDeliveryDate?: string;
    /**
     * Carrier display name
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    carrierName?: string;
    /**
     * Carrier slug identifier
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    carrierSlug?: string;
    /**
     * Carrier product ID
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    productId?: string;
    /**
     * Shipping rule ID that generated this rate
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    shippingRuleId: string;
}

/**
 * Check if a given object implements the CreateShippingQuote200ResponseRatesInner interface.
 */
export function instanceOfCreateShippingQuote200ResponseRatesInner(value: object): value is CreateShippingQuote200ResponseRatesInner {
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('serviceCode' in value) || value['serviceCode'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('shippingRuleId' in value) || value['shippingRuleId'] === undefined) return false;
    return true;
}

export function CreateShippingQuote200ResponseRatesInnerFromJSON(json: any): CreateShippingQuote200ResponseRatesInner {
    return CreateShippingQuote200ResponseRatesInnerFromJSONTyped(json, false);
}

export function CreateShippingQuote200ResponseRatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShippingQuote200ResponseRatesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'],
        'serviceCode': json['serviceCode'],
        'totalPrice': json['totalPrice'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'minDeliveryDate': json['minDeliveryDate'] == null ? undefined : json['minDeliveryDate'],
        'maxDeliveryDate': json['maxDeliveryDate'] == null ? undefined : json['maxDeliveryDate'],
        'carrierName': json['carrierName'] == null ? undefined : json['carrierName'],
        'carrierSlug': json['carrierSlug'] == null ? undefined : json['carrierSlug'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'shippingRuleId': json['shippingRuleId'],
    };
}

export function CreateShippingQuote200ResponseRatesInnerToJSON(json: any): CreateShippingQuote200ResponseRatesInner {
    return CreateShippingQuote200ResponseRatesInnerToJSONTyped(json, false);
}

export function CreateShippingQuote200ResponseRatesInnerToJSONTyped(value?: CreateShippingQuote200ResponseRatesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceName': value['serviceName'],
        'serviceCode': value['serviceCode'],
        'totalPrice': value['totalPrice'],
        'currency': value['currency'],
        'description': value['description'],
        'minDeliveryDate': value['minDeliveryDate'],
        'maxDeliveryDate': value['maxDeliveryDate'],
        'carrierName': value['carrierName'],
        'carrierSlug': value['carrierSlug'],
        'productId': value['productId'],
        'shippingRuleId': value['shippingRuleId'],
    };
}

