/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShipment201ResponseLogsInner
 */
export interface CreateShipment201ResponseLogsInner {
    /**
     * Unique log entry identifier.
     * @type {string}
     * @memberof CreateShipment201ResponseLogsInner
     */
    id: string;
    /**
     * Direction of the logged request.
     * @type {CreateShipment201ResponseLogsInnerDirectionEnum}
     * @memberof CreateShipment201ResponseLogsInner
     */
    direction: CreateShipment201ResponseLogsInnerDirectionEnum;
    /**
     * Captured request payload.
     * @type {any}
     * @memberof CreateShipment201ResponseLogsInner
     */
    request: any | null;
    /**
     * Captured response payload.
     * @type {any}
     * @memberof CreateShipment201ResponseLogsInner
     */
    response?: any | null;
    /**
     * HTTP status code of the response.
     * @type {number}
     * @memberof CreateShipment201ResponseLogsInner
     */
    statusCode?: number | null;
    /**
     * Error message if the request failed.
     * @type {string}
     * @memberof CreateShipment201ResponseLogsInner
     */
    error?: string | null;
    /**
     * Request duration in milliseconds.
     * @type {number}
     * @memberof CreateShipment201ResponseLogsInner
     */
    duration?: number | null;
    /**
     * Timestamp when the log entry was created.
     * @type {string}
     * @memberof CreateShipment201ResponseLogsInner
     */
    createdAt: string;
}


/**
 * @export
 */
export const CreateShipment201ResponseLogsInnerDirectionEnum = {
    Inbound: 'inbound',
    Outbound: 'outbound',
    Carrier: 'carrier'
} as const;
export type CreateShipment201ResponseLogsInnerDirectionEnum = typeof CreateShipment201ResponseLogsInnerDirectionEnum[keyof typeof CreateShipment201ResponseLogsInnerDirectionEnum];


/**
 * Check if a given object implements the CreateShipment201ResponseLogsInner interface.
 */
export function instanceOfCreateShipment201ResponseLogsInner(value: object): value is CreateShipment201ResponseLogsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateShipment201ResponseLogsInnerFromJSON(json: any): CreateShipment201ResponseLogsInner {
    return CreateShipment201ResponseLogsInnerFromJSONTyped(json, false);
}

export function CreateShipment201ResponseLogsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShipment201ResponseLogsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'direction': json['direction'],
        'request': json['request'],
        'response': json['response'] === undefined ? undefined : json['response'] === null ? null : json['response'],
        'statusCode': json['statusCode'] === undefined ? undefined : json['statusCode'] === null ? null : json['statusCode'],
        'error': json['error'] === undefined ? undefined : json['error'] === null ? null : json['error'],
        'duration': json['duration'] === undefined ? undefined : json['duration'] === null ? null : json['duration'],
        'createdAt': json['createdAt'],
    };
}

export function CreateShipment201ResponseLogsInnerToJSON(json: any): CreateShipment201ResponseLogsInner {
    return CreateShipment201ResponseLogsInnerToJSONTyped(json, false);
}

export function CreateShipment201ResponseLogsInnerToJSONTyped(value?: CreateShipment201ResponseLogsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'direction': value['direction'],
        'request': value['request'],
        'response': value['response'],
        'statusCode': value['statusCode'],
        'error': value['error'],
        'duration': value['duration'],
        'createdAt': value['createdAt'],
    };
}

