/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrgWebhook201Response
 */
export interface CreateOrgWebhook201Response {
    /**
     * Webhook ID
     * @type {string}
     * @memberof CreateOrgWebhook201Response
     */
    id: string;
    /**
     * Human-readable webhook name
     * @type {string}
     * @memberof CreateOrgWebhook201Response
     */
    name: string;
    /**
     * Webhook endpoint URL
     * @type {string}
     * @memberof CreateOrgWebhook201Response
     */
    url: string;
    /**
     * Signing secret used to verify webhook payloads
     * @type {string}
     * @memberof CreateOrgWebhook201Response
     */
    secret: string;
    /**
     * Events the webhook is subscribed to
     * @type {Array<string>}
     * @memberof CreateOrgWebhook201Response
     */
    events: Array<string>;
    /**
     * Whether the webhook is active
     * @type {boolean}
     * @memberof CreateOrgWebhook201Response
     */
    isActive: boolean;
    /**
     * Creation timestamp (ISO 8601)
     * @type {string}
     * @memberof CreateOrgWebhook201Response
     */
    createdAt: string;
    /**
     * Last update timestamp (ISO 8601)
     * @type {string}
     * @memberof CreateOrgWebhook201Response
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the CreateOrgWebhook201Response interface.
 */
export function instanceOfCreateOrgWebhook201Response(value: object): value is CreateOrgWebhook201Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CreateOrgWebhook201ResponseFromJSON(json: any): CreateOrgWebhook201Response {
    return CreateOrgWebhook201ResponseFromJSONTyped(json, false);
}

export function CreateOrgWebhook201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrgWebhook201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'secret': json['secret'],
        'events': json['events'],
        'isActive': json['isActive'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CreateOrgWebhook201ResponseToJSON(json: any): CreateOrgWebhook201Response {
    return CreateOrgWebhook201ResponseToJSONTyped(json, false);
}

export function CreateOrgWebhook201ResponseToJSONTyped(value?: CreateOrgWebhook201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
        'secret': value['secret'],
        'events': value['events'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

