/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShipment201ResponsePickupDetails
 */
export interface CreateShipment201ResponsePickupDetails {
    /**
     * Requested pickup date (YYYY-MM-DD).
     * @type {string}
     * @memberof CreateShipment201ResponsePickupDetails
     */
    date: string;
    /**
     * Requested earliest pickup time (HH:MM:SS).
     * @type {string}
     * @memberof CreateShipment201ResponsePickupDetails
     */
    from: string;
    /**
     * Requested latest pickup time (HH:MM:SS).
     * @type {string}
     * @memberof CreateShipment201ResponsePickupDetails
     */
    to: string;
    /**
     * Pickup instruction to the carrier.
     * @type {string}
     * @memberof CreateShipment201ResponsePickupDetails
     */
    instruction?: string;
}

/**
 * Check if a given object implements the CreateShipment201ResponsePickupDetails interface.
 */
export function instanceOfCreateShipment201ResponsePickupDetails(value: object): value is CreateShipment201ResponsePickupDetails {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function CreateShipment201ResponsePickupDetailsFromJSON(json: any): CreateShipment201ResponsePickupDetails {
    return CreateShipment201ResponsePickupDetailsFromJSONTyped(json, false);
}

export function CreateShipment201ResponsePickupDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShipment201ResponsePickupDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'from': json['from'],
        'to': json['to'],
        'instruction': json['instruction'] == null ? undefined : json['instruction'],
    };
}

export function CreateShipment201ResponsePickupDetailsToJSON(json: any): CreateShipment201ResponsePickupDetails {
    return CreateShipment201ResponsePickupDetailsToJSONTyped(json, false);
}

export function CreateShipment201ResponsePickupDetailsToJSONTyped(value?: CreateShipment201ResponsePickupDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'from': value['from'],
        'to': value['to'],
        'instruction': value['instruction'],
    };
}

