/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiTokenRequest
 */
export interface CreateApiTokenRequest {
    /**
     * Token name for identification
     * @type {string}
     * @memberof CreateApiTokenRequest
     */
    name: string;
    /**
     * Permission scopes for the token
     * @type {Array<CreateApiTokenRequestScopesEnum>}
     * @memberof CreateApiTokenRequest
     */
    scopes: Array<CreateApiTokenRequestScopesEnum>;
    /**
     * Token expiry in days (optional, max 365)
     * @type {number}
     * @memberof CreateApiTokenRequest
     */
    expiresInDays?: number;
}


/**
 * @export
 */
export const CreateApiTokenRequestScopesEnum = {
    ReadApiTokens: 'read:api_tokens',
    WriteApiTokens: 'write:api_tokens',
    ReadOrgs: 'read:orgs',
    WriteOrgs: 'write:orgs',
    ReadUsers: 'read:users',
    WriteUsers: 'write:users',
    ReadRoles: 'read:roles',
    WriteRoles: 'write:roles',
    ReadOrgMembers: 'read:org_members',
    WriteOrgMembers: 'write:org_members',
    ReadCarriers: 'read:carriers',
    WriteCarriers: 'write:carriers',
    ReadAddresses: 'read:addresses',
    WriteAddresses: 'write:addresses',
    ReadShippingRules: 'read:shipping_rules',
    WriteShippingRules: 'write:shipping_rules',
    ReadShipments: 'read:shipments',
    WriteShipments: 'write:shipments',
    ReadOrders: 'read:orders',
    WriteOrders: 'write:orders',
    ReadOrderChannels: 'read:order_channels',
    WriteOrderChannels: 'write:order_channels',
    ReadReturnPortals: 'read:return_portals',
    WriteReturnPortals: 'write:return_portals',
    ReadPrinters: 'read:printers',
    WritePrinters: 'write:printers',
    ReadWebhooks: 'read:webhooks',
    WriteWebhooks: 'write:webhooks',
    ReadAutomations: 'read:automations',
    WriteAutomations: 'write:automations',
    ReadIntegrations: 'read:integrations',
    WriteIntegrations: 'write:integrations',
    ReadAll: 'read:all',
    WriteAll: 'write:all'
} as const;
export type CreateApiTokenRequestScopesEnum = typeof CreateApiTokenRequestScopesEnum[keyof typeof CreateApiTokenRequestScopesEnum];


/**
 * Check if a given object implements the CreateApiTokenRequest interface.
 */
export function instanceOfCreateApiTokenRequest(value: object): value is CreateApiTokenRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    return true;
}

export function CreateApiTokenRequestFromJSON(json: any): CreateApiTokenRequest {
    return CreateApiTokenRequestFromJSONTyped(json, false);
}

export function CreateApiTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'scopes': json['scopes'],
        'expiresInDays': json['expiresInDays'] == null ? undefined : json['expiresInDays'],
    };
}

export function CreateApiTokenRequestToJSON(json: any): CreateApiTokenRequest {
    return CreateApiTokenRequestToJSONTyped(json, false);
}

export function CreateApiTokenRequestToJSONTyped(value?: CreateApiTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'scopes': value['scopes'],
        'expiresInDays': value['expiresInDays'],
    };
}

