/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShipment201ResponseTracking
 */
export interface CreateShipment201ResponseTracking {
    /**
     * Public carrier tracking URL.
     * @type {string}
     * @memberof CreateShipment201ResponseTracking
     */
    url?: string | null;
    /**
     * Carrier tracking number.
     * @type {string}
     * @memberof CreateShipment201ResponseTracking
     */
    number?: string | null;
    /**
     * Label-free drop-off code.
     * @type {string}
     * @memberof CreateShipment201ResponseTracking
     */
    labelFreeCode?: string | null;
    /**
     * DEPRECATED — use `qrCodeDataUri` (embeddable data URI) or `qrCodeUrl` (hosted link). Catch-all that carries whichever applies, kept populated for backwards compatibility during the migration and until it is disabled.
     * @type {string}
     * @memberof CreateShipment201ResponseTracking
     */
    qrCodeLink?: string | null;
    /**
     * Embeddable `data:` URI of the QR code image for label-free drop-off — base64 image bytes you can drop straight into an <img>/email. Null when the carrier returns a hosted link instead (see `qrCodeUrl`).
     * @type {string}
     * @memberof CreateShipment201ResponseTracking
     */
    qrCodeDataUri?: string | null;
    /**
     * Carrier-hosted URL of the QR code image for label-free drop-off, returned by carriers (e.g. Bring) that link to the image rather than embedding it. Null when the carrier returns embeddable bytes (see `qrCodeDataUri`).
     * @type {string}
     * @memberof CreateShipment201ResponseTracking
     */
    qrCodeUrl?: string | null;
}

/**
 * Check if a given object implements the CreateShipment201ResponseTracking interface.
 */
export function instanceOfCreateShipment201ResponseTracking(value: object): value is CreateShipment201ResponseTracking {
    return true;
}

export function CreateShipment201ResponseTrackingFromJSON(json: any): CreateShipment201ResponseTracking {
    return CreateShipment201ResponseTrackingFromJSONTyped(json, false);
}

export function CreateShipment201ResponseTrackingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShipment201ResponseTracking {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] === undefined ? undefined : json['url'] === null ? null : json['url'],
        'number': json['number'] === undefined ? undefined : json['number'] === null ? null : json['number'],
        'labelFreeCode': json['labelFreeCode'] === undefined ? undefined : json['labelFreeCode'] === null ? null : json['labelFreeCode'],
        'qrCodeLink': json['qrCodeLink'] === undefined ? undefined : json['qrCodeLink'] === null ? null : json['qrCodeLink'],
        'qrCodeDataUri': json['qrCodeDataUri'] === undefined ? undefined : json['qrCodeDataUri'] === null ? null : json['qrCodeDataUri'],
        'qrCodeUrl': json['qrCodeUrl'] === undefined ? undefined : json['qrCodeUrl'] === null ? null : json['qrCodeUrl'],
    };
}

export function CreateShipment201ResponseTrackingToJSON(json: any): CreateShipment201ResponseTracking {
    return CreateShipment201ResponseTrackingToJSONTyped(json, false);
}

export function CreateShipment201ResponseTrackingToJSONTyped(value?: CreateShipment201ResponseTracking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'number': value['number'],
        'labelFreeCode': value['labelFreeCode'],
        'qrCodeLink': value['qrCodeLink'],
        'qrCodeDataUri': value['qrCodeDataUri'],
        'qrCodeUrl': value['qrCodeUrl'],
    };
}

