/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShippingQuote200ResponseRatesInner
 */
export interface CreateShippingQuote200ResponseRatesInner {
    /**
     * Display name of the shipping option
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    serviceName: string;
    /**
     * Unique identifier for this shipping option
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    serviceCode: string;
    /**
     * Total shipping price in cents as string
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    totalPrice: string;
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    currency: string;
    /**
     * Optional description
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    description?: string;
    /**
     * Minimum delivery date (ISO 8601)
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    minDeliveryDate?: string;
    /**
     * Maximum delivery date (ISO 8601)
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    maxDeliveryDate?: string;
    /**
     * Carrier display name
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    carrierName?: string;
    /**
     * Carrier slug identifier
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    carrierSlug?: string;
    /**
     * Carrier product ID
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    productId?: string;
    /**
     * Shipping rule ID that generated this rate
     * @type {string}
     * @memberof CreateShippingQuote200ResponseRatesInner
     */
    shippingRuleId: string;
}

/**
 * Check if a given object implements the CreateShippingQuote200ResponseRatesInner interface.
 */
export function instanceOfCreateShippingQuote200ResponseRatesInner(value: object): value is CreateShippingQuote200ResponseRatesInner {
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('serviceCode' in value) || value['serviceCode'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('shippingRuleId' in value) || value['shippingRuleId'] === undefined) return false;
    return true;
}

export function CreateShippingQuote200ResponseRatesInnerFromJSON(json: any): CreateShippingQuote200ResponseRatesInner {
    return CreateShippingQuote200ResponseRatesInnerFromJSONTyped(json, false);
}

export function CreateShippingQuote200ResponseRatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShippingQuote200ResponseRatesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'],
        'serviceCode': json['serviceCode'],
        'totalPrice': json['totalPrice'],
        'currency': json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'minDeliveryDate': json['minDeliveryDate'] == null ? undefined : json['minDeliveryDate'],
        'maxDeliveryDate': json['maxDeliveryDate'] == null ? undefined : json['maxDeliveryDate'],
        'carrierName': json['carrierName'] == null ? undefined : json['carrierName'],
        'carrierSlug': json['carrierSlug'] == null ? undefined : json['carrierSlug'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'shippingRuleId': json['shippingRuleId'],
    };
}

export function CreateShippingQuote200ResponseRatesInnerToJSON(json: any): CreateShippingQuote200ResponseRatesInner {
    return CreateShippingQuote200ResponseRatesInnerToJSONTyped(json, false);
}

export function CreateShippingQuote200ResponseRatesInnerToJSONTyped(value?: CreateShippingQuote200ResponseRatesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceName': value['serviceName'],
        'serviceCode': value['serviceCode'],
        'totalPrice': value['totalPrice'],
        'currency': value['currency'],
        'description': value['description'],
        'minDeliveryDate': value['minDeliveryDate'],
        'maxDeliveryDate': value['maxDeliveryDate'],
        'carrierName': value['carrierName'],
        'carrierSlug': value['carrierSlug'],
        'productId': value['productId'],
        'shippingRuleId': value['shippingRuleId'],
    };
}

