/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateShippingRuleRequestConditionsInnerOneOf } from './CreateShippingRuleRequestConditionsInnerOneOf';
import {
    instanceOfCreateShippingRuleRequestConditionsInnerOneOf,
    CreateShippingRuleRequestConditionsInnerOneOfFromJSON,
    CreateShippingRuleRequestConditionsInnerOneOfFromJSONTyped,
    CreateShippingRuleRequestConditionsInnerOneOfToJSON,
} from './CreateShippingRuleRequestConditionsInnerOneOf';
import type { CreateShippingRuleRequestConditionsInnerOneOf1 } from './CreateShippingRuleRequestConditionsInnerOneOf1';
import {
    instanceOfCreateShippingRuleRequestConditionsInnerOneOf1,
    CreateShippingRuleRequestConditionsInnerOneOf1FromJSON,
    CreateShippingRuleRequestConditionsInnerOneOf1FromJSONTyped,
    CreateShippingRuleRequestConditionsInnerOneOf1ToJSON,
} from './CreateShippingRuleRequestConditionsInnerOneOf1';
import type { CreateShippingRuleRequestConditionsInnerOneOf2 } from './CreateShippingRuleRequestConditionsInnerOneOf2';
import {
    instanceOfCreateShippingRuleRequestConditionsInnerOneOf2,
    CreateShippingRuleRequestConditionsInnerOneOf2FromJSON,
    CreateShippingRuleRequestConditionsInnerOneOf2FromJSONTyped,
    CreateShippingRuleRequestConditionsInnerOneOf2ToJSON,
} from './CreateShippingRuleRequestConditionsInnerOneOf2';
import type { CreateShippingRuleRequestConditionsInnerOneOf3 } from './CreateShippingRuleRequestConditionsInnerOneOf3';
import {
    instanceOfCreateShippingRuleRequestConditionsInnerOneOf3,
    CreateShippingRuleRequestConditionsInnerOneOf3FromJSON,
    CreateShippingRuleRequestConditionsInnerOneOf3FromJSONTyped,
    CreateShippingRuleRequestConditionsInnerOneOf3ToJSON,
} from './CreateShippingRuleRequestConditionsInnerOneOf3';
import type { CreateShippingRuleRequestConditionsInnerOneOf4 } from './CreateShippingRuleRequestConditionsInnerOneOf4';
import {
    instanceOfCreateShippingRuleRequestConditionsInnerOneOf4,
    CreateShippingRuleRequestConditionsInnerOneOf4FromJSON,
    CreateShippingRuleRequestConditionsInnerOneOf4FromJSONTyped,
    CreateShippingRuleRequestConditionsInnerOneOf4ToJSON,
} from './CreateShippingRuleRequestConditionsInnerOneOf4';

/**
 * @type CreateShippingRuleRequestConditionsInner
 * 
 * @export
 */
export type CreateShippingRuleRequestConditionsInner = CreateShippingRuleRequestConditionsInnerOneOf | CreateShippingRuleRequestConditionsInnerOneOf1 | CreateShippingRuleRequestConditionsInnerOneOf2 | CreateShippingRuleRequestConditionsInnerOneOf3 | CreateShippingRuleRequestConditionsInnerOneOf4;

export function CreateShippingRuleRequestConditionsInnerFromJSON(json: any): CreateShippingRuleRequestConditionsInner {
    return CreateShippingRuleRequestConditionsInnerFromJSONTyped(json, false);
}

export function CreateShippingRuleRequestConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShippingRuleRequestConditionsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf(json)) {
        return CreateShippingRuleRequestConditionsInnerOneOfFromJSONTyped(json, true);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf1(json)) {
        return CreateShippingRuleRequestConditionsInnerOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf2(json)) {
        return CreateShippingRuleRequestConditionsInnerOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf3(json)) {
        return CreateShippingRuleRequestConditionsInnerOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf4(json)) {
        return CreateShippingRuleRequestConditionsInnerOneOf4FromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateShippingRuleRequestConditionsInnerToJSON(json: any): any {
    return CreateShippingRuleRequestConditionsInnerToJSONTyped(json, false);
}

export function CreateShippingRuleRequestConditionsInnerToJSONTyped(value?: CreateShippingRuleRequestConditionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf(value)) {
        return CreateShippingRuleRequestConditionsInnerOneOfToJSON(value as CreateShippingRuleRequestConditionsInnerOneOf);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf1(value)) {
        return CreateShippingRuleRequestConditionsInnerOneOf1ToJSON(value as CreateShippingRuleRequestConditionsInnerOneOf1);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf2(value)) {
        return CreateShippingRuleRequestConditionsInnerOneOf2ToJSON(value as CreateShippingRuleRequestConditionsInnerOneOf2);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf3(value)) {
        return CreateShippingRuleRequestConditionsInnerOneOf3ToJSON(value as CreateShippingRuleRequestConditionsInnerOneOf3);
    }
    if (instanceOfCreateShippingRuleRequestConditionsInnerOneOf4(value)) {
        return CreateShippingRuleRequestConditionsInnerOneOf4ToJSON(value as CreateShippingRuleRequestConditionsInnerOneOf4);
    }
    return {};
}

