/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateShipment201ResponseParcelsInnerOrderLinesInner } from './CreateShipment201ResponseParcelsInnerOrderLinesInner';
import {
    CreateShipment201ResponseParcelsInnerOrderLinesInnerFromJSON,
    CreateShipment201ResponseParcelsInnerOrderLinesInnerFromJSONTyped,
    CreateShipment201ResponseParcelsInnerOrderLinesInnerToJSON,
    CreateShipment201ResponseParcelsInnerOrderLinesInnerToJSONTyped,
} from './CreateShipment201ResponseParcelsInnerOrderLinesInner';
import type { CreateShipment201ResponseParcelsInnerDimensions } from './CreateShipment201ResponseParcelsInnerDimensions';
import {
    CreateShipment201ResponseParcelsInnerDimensionsFromJSON,
    CreateShipment201ResponseParcelsInnerDimensionsFromJSONTyped,
    CreateShipment201ResponseParcelsInnerDimensionsToJSON,
    CreateShipment201ResponseParcelsInnerDimensionsToJSONTyped,
} from './CreateShipment201ResponseParcelsInnerDimensions';

/**
 * 
 * @export
 * @interface CreateShipment201ResponseParcelsInner
 */
export interface CreateShipment201ResponseParcelsInner {
    /**
     * Unique parcel identifier.
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    id?: string;
    /**
     * Parcel weight in the given weight unit.
     * @type {number}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    weight: number;
    /**
     * Unit of measurement for parcel weight.
     * @type {CreateShipment201ResponseParcelsInnerWeightUnitEnum}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    weightUnit: CreateShipment201ResponseParcelsInnerWeightUnitEnum;
    /**
     * 
     * @type {CreateShipment201ResponseParcelsInnerDimensions}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    dimensions: CreateShipment201ResponseParcelsInnerDimensions;
    /**
     * Order lines contained in this parcel.
     * @type {Array<CreateShipment201ResponseParcelsInnerOrderLinesInner>}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    orderLines: Array<CreateShipment201ResponseParcelsInnerOrderLinesInner>;
    /**
     * Carrier tracking number for this parcel.
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    trackingNumber?: string | null;
    /**
     * Public carrier tracking URL for this parcel.
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    trackingUrl?: string | null;
    /**
     * Label-free drop-off code for the parcel.
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    labelFreeCode?: string | null;
    /**
     * DEPRECATED — use `qrCodeDataUri` (embeddable data URI) or `qrCodeUrl` (hosted link). Catch-all that carries whichever applies, kept populated for backwards compatibility during the migration and until it is disabled.
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    qrCodeLink?: string | null;
    /**
     * Embeddable `data:` URI of the QR code image for label-free drop-off — base64 image bytes you can drop straight into an <img>/email. Null when the carrier returns a hosted link instead (see `qrCodeUrl`).
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    qrCodeDataUri?: string | null;
    /**
     * Carrier-hosted URL of the QR code image for label-free drop-off, returned by carriers (e.g. Bring) that link to the image rather than embedding it. Null when the carrier returns embeddable bytes (see `qrCodeDataUri`).
     * @type {string}
     * @memberof CreateShipment201ResponseParcelsInner
     */
    qrCodeUrl?: string | null;
}


/**
 * @export
 */
export const CreateShipment201ResponseParcelsInnerWeightUnitEnum = {
    Kg: 'kg',
    G: 'g',
    Lb: 'lb',
    Oz: 'oz'
} as const;
export type CreateShipment201ResponseParcelsInnerWeightUnitEnum = typeof CreateShipment201ResponseParcelsInnerWeightUnitEnum[keyof typeof CreateShipment201ResponseParcelsInnerWeightUnitEnum];


/**
 * Check if a given object implements the CreateShipment201ResponseParcelsInner interface.
 */
export function instanceOfCreateShipment201ResponseParcelsInner(value: object): value is CreateShipment201ResponseParcelsInner {
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('weightUnit' in value) || value['weightUnit'] === undefined) return false;
    if (!('dimensions' in value) || value['dimensions'] === undefined) return false;
    if (!('orderLines' in value) || value['orderLines'] === undefined) return false;
    return true;
}

export function CreateShipment201ResponseParcelsInnerFromJSON(json: any): CreateShipment201ResponseParcelsInner {
    return CreateShipment201ResponseParcelsInnerFromJSONTyped(json, false);
}

export function CreateShipment201ResponseParcelsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShipment201ResponseParcelsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'weight': json['weight'],
        'weightUnit': json['weightUnit'],
        'dimensions': CreateShipment201ResponseParcelsInnerDimensionsFromJSON(json['dimensions']),
        'orderLines': ((json['orderLines'] as Array<any>).map(CreateShipment201ResponseParcelsInnerOrderLinesInnerFromJSON)),
        'trackingNumber': json['trackingNumber'] === undefined ? undefined : json['trackingNumber'] === null ? null : json['trackingNumber'],
        'trackingUrl': json['trackingUrl'] === undefined ? undefined : json['trackingUrl'] === null ? null : json['trackingUrl'],
        'labelFreeCode': json['labelFreeCode'] === undefined ? undefined : json['labelFreeCode'] === null ? null : json['labelFreeCode'],
        'qrCodeLink': json['qrCodeLink'] === undefined ? undefined : json['qrCodeLink'] === null ? null : json['qrCodeLink'],
        'qrCodeDataUri': json['qrCodeDataUri'] === undefined ? undefined : json['qrCodeDataUri'] === null ? null : json['qrCodeDataUri'],
        'qrCodeUrl': json['qrCodeUrl'] === undefined ? undefined : json['qrCodeUrl'] === null ? null : json['qrCodeUrl'],
    };
}

export function CreateShipment201ResponseParcelsInnerToJSON(json: any): CreateShipment201ResponseParcelsInner {
    return CreateShipment201ResponseParcelsInnerToJSONTyped(json, false);
}

export function CreateShipment201ResponseParcelsInnerToJSONTyped(value?: CreateShipment201ResponseParcelsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'weight': value['weight'],
        'weightUnit': value['weightUnit'],
        'dimensions': CreateShipment201ResponseParcelsInnerDimensionsToJSON(value['dimensions']),
        'orderLines': ((value['orderLines'] as Array<any>).map(CreateShipment201ResponseParcelsInnerOrderLinesInnerToJSON)),
        'trackingNumber': value['trackingNumber'],
        'trackingUrl': value['trackingUrl'],
        'labelFreeCode': value['labelFreeCode'],
        'qrCodeLink': value['qrCodeLink'],
        'qrCodeDataUri': value['qrCodeDataUri'],
        'qrCodeUrl': value['qrCodeUrl'],
    };
}

