/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Destination shipping address.
 * @export
 * @interface CreateOrderRequestShippingAddress
 */
export interface CreateOrderRequestShippingAddress {
    /**
     * Recipient full name.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    name: string;
    /**
     * Attention / care-of line.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    attention?: string | null;
    /**
     * Company name.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    company?: string | null;
    /**
     * Street address line 1.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    address1: string;
    /**
     * Street address line 2.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    address2?: string | null;
    /**
     * City name.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    city: string;
    /**
     * Province or region name.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    province?: string | null;
    /**
     * Province or region code.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    provinceCode?: string | null;
    /**
     * Postal code.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    postalCode: string;
    /**
     * Country name.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    country?: string | null;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    countryCode: string;
    /**
     * Recipient phone number.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    phone?: string | null;
    /**
     * Recipient email address.
     * @type {string}
     * @memberof CreateOrderRequestShippingAddress
     */
    email?: string | null;
}

/**
 * Check if a given object implements the CreateOrderRequestShippingAddress interface.
 */
export function instanceOfCreateOrderRequestShippingAddress(value: object): value is CreateOrderRequestShippingAddress {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address1' in value) || value['address1'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    return true;
}

export function CreateOrderRequestShippingAddressFromJSON(json: any): CreateOrderRequestShippingAddress {
    return CreateOrderRequestShippingAddressFromJSONTyped(json, false);
}

export function CreateOrderRequestShippingAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderRequestShippingAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'attention': json['attention'] === undefined ? undefined : json['attention'] === null ? null : json['attention'],
        'company': json['company'] === undefined ? undefined : json['company'] === null ? null : json['company'],
        'address1': json['address1'],
        'address2': json['address2'] === undefined ? undefined : json['address2'] === null ? null : json['address2'],
        'city': json['city'],
        'province': json['province'] === undefined ? undefined : json['province'] === null ? null : json['province'],
        'provinceCode': json['provinceCode'] === undefined ? undefined : json['provinceCode'] === null ? null : json['provinceCode'],
        'postalCode': json['postalCode'],
        'country': json['country'] === undefined ? undefined : json['country'] === null ? null : json['country'],
        'countryCode': json['countryCode'],
        'phone': json['phone'] === undefined ? undefined : json['phone'] === null ? null : json['phone'],
        'email': json['email'] === undefined ? undefined : json['email'] === null ? null : json['email'],
    };
}

export function CreateOrderRequestShippingAddressToJSON(json: any): CreateOrderRequestShippingAddress {
    return CreateOrderRequestShippingAddressToJSONTyped(json, false);
}

export function CreateOrderRequestShippingAddressToJSONTyped(value?: CreateOrderRequestShippingAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'attention': value['attention'],
        'company': value['company'],
        'address1': value['address1'],
        'address2': value['address2'],
        'city': value['city'],
        'province': value['province'],
        'provinceCode': value['provinceCode'],
        'postalCode': value['postalCode'],
        'country': value['country'],
        'countryCode': value['countryCode'],
        'phone': value['phone'],
        'email': value['email'],
    };
}

