/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateShippingRuleRequestAdditionalParametersAnyOfValue } from './CreateShippingRuleRequestAdditionalParametersAnyOfValue';
import {
    CreateShippingRuleRequestAdditionalParametersAnyOfValueFromJSON,
    CreateShippingRuleRequestAdditionalParametersAnyOfValueFromJSONTyped,
    CreateShippingRuleRequestAdditionalParametersAnyOfValueToJSON,
    CreateShippingRuleRequestAdditionalParametersAnyOfValueToJSONTyped,
} from './CreateShippingRuleRequestAdditionalParametersAnyOfValue';

/**
 * 
 * @export
 * @interface CreateShipmentRequestCarrierSettings
 */
export interface CreateShipmentRequestCarrierSettings {
    /**
     * Identifier of the carrier to use.
     * @type {string}
     * @memberof CreateShipmentRequestCarrierSettings
     */
    carrierId: string;
    /**
     * Identifier of the carrier product/service.
     * @type {string}
     * @memberof CreateShipmentRequestCarrierSettings
     */
    productId: string;
    /**
     * Additional service codes requested from the carrier.
     * @type {Array<string>}
     * @memberof CreateShipmentRequestCarrierSettings
     */
    services: Array<string>;
    /**
     * Carrier-specific extra parameters as key/value pairs.
     * @type {{ [key: string]: CreateShippingRuleRequestAdditionalParametersAnyOfValue; }}
     * @memberof CreateShipmentRequestCarrierSettings
     */
    additionalParameters: { [key: string]: CreateShippingRuleRequestAdditionalParametersAnyOfValue; };
}

/**
 * Check if a given object implements the CreateShipmentRequestCarrierSettings interface.
 */
export function instanceOfCreateShipmentRequestCarrierSettings(value: object): value is CreateShipmentRequestCarrierSettings {
    if (!('carrierId' in value) || value['carrierId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    if (!('additionalParameters' in value) || value['additionalParameters'] === undefined) return false;
    return true;
}

export function CreateShipmentRequestCarrierSettingsFromJSON(json: any): CreateShipmentRequestCarrierSettings {
    return CreateShipmentRequestCarrierSettingsFromJSONTyped(json, false);
}

export function CreateShipmentRequestCarrierSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShipmentRequestCarrierSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'carrierId': json['carrierId'],
        'productId': json['productId'],
        'services': json['services'],
        'additionalParameters': (mapValues(json['additionalParameters'], CreateShippingRuleRequestAdditionalParametersAnyOfValueFromJSON)),
    };
}

export function CreateShipmentRequestCarrierSettingsToJSON(json: any): CreateShipmentRequestCarrierSettings {
    return CreateShipmentRequestCarrierSettingsToJSONTyped(json, false);
}

export function CreateShipmentRequestCarrierSettingsToJSONTyped(value?: CreateShipmentRequestCarrierSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrierId': value['carrierId'],
        'productId': value['productId'],
        'services': value['services'],
        'additionalParameters': (mapValues(value['additionalParameters'], CreateShippingRuleRequestAdditionalParametersAnyOfValueToJSON)),
    };
}

