/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShippingQuote404Response
 */
export interface CreateShippingQuote404Response {
    /**
     * Error type
     * @type {string}
     * @memberof CreateShippingQuote404Response
     */
    error: string;
    /**
     * Human-readable error message
     * @type {string}
     * @memberof CreateShippingQuote404Response
     */
    message: string;
}

/**
 * Check if a given object implements the CreateShippingQuote404Response interface.
 */
export function instanceOfCreateShippingQuote404Response(value: object): value is CreateShippingQuote404Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateShippingQuote404ResponseFromJSON(json: any): CreateShippingQuote404Response {
    return CreateShippingQuote404ResponseFromJSONTyped(json, false);
}

export function CreateShippingQuote404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShippingQuote404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'message': json['message'],
    };
}

export function CreateShippingQuote404ResponseToJSON(json: any): CreateShippingQuote404Response {
    return CreateShippingQuote404ResponseToJSONTyped(json, false);
}

export function CreateShippingQuote404ResponseToJSONTyped(value?: CreateShippingQuote404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

