/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteOrgWebhook200Response
 */
export interface DeleteOrgWebhook200Response {
    /**
     * Result message
     * @type {string}
     * @memberof DeleteOrgWebhook200Response
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteOrgWebhook200Response interface.
 */
export function instanceOfDeleteOrgWebhook200Response(value: object): value is DeleteOrgWebhook200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteOrgWebhook200ResponseFromJSON(json: any): DeleteOrgWebhook200Response {
    return DeleteOrgWebhook200ResponseFromJSONTyped(json, false);
}

export function DeleteOrgWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteOrgWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DeleteOrgWebhook200ResponseToJSON(json: any): DeleteOrgWebhook200Response {
    return DeleteOrgWebhook200ResponseToJSONTyped(json, false);
}

export function DeleteOrgWebhook200ResponseToJSONTyped(value?: DeleteOrgWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

