/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBillingUsage200ResponseShipments
 */
export interface GetBillingUsage200ResponseShipments {
    /**
     * Shipments created this period
     * @type {number}
     * @memberof GetBillingUsage200ResponseShipments
     */
    used: number;
    /**
     * Shipments included in the plan
     * @type {number}
     * @memberof GetBillingUsage200ResponseShipments
     */
    included: number;
    /**
     * Shipments above the included allowance
     * @type {number}
     * @memberof GetBillingUsage200ResponseShipments
     */
    overage: number;
    /**
     * Overage charges so far, in øre
     * @type {number}
     * @memberof GetBillingUsage200ResponseShipments
     */
    overageCharges: number;
}

/**
 * Check if a given object implements the GetBillingUsage200ResponseShipments interface.
 */
export function instanceOfGetBillingUsage200ResponseShipments(value: object): value is GetBillingUsage200ResponseShipments {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('included' in value) || value['included'] === undefined) return false;
    if (!('overage' in value) || value['overage'] === undefined) return false;
    if (!('overageCharges' in value) || value['overageCharges'] === undefined) return false;
    return true;
}

export function GetBillingUsage200ResponseShipmentsFromJSON(json: any): GetBillingUsage200ResponseShipments {
    return GetBillingUsage200ResponseShipmentsFromJSONTyped(json, false);
}

export function GetBillingUsage200ResponseShipmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingUsage200ResponseShipments {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'included': json['included'],
        'overage': json['overage'],
        'overageCharges': json['overageCharges'],
    };
}

export function GetBillingUsage200ResponseShipmentsToJSON(json: any): GetBillingUsage200ResponseShipments {
    return GetBillingUsage200ResponseShipmentsToJSONTyped(json, false);
}

export function GetBillingUsage200ResponseShipmentsToJSONTyped(value?: GetBillingUsage200ResponseShipments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'used': value['used'],
        'included': value['included'],
        'overage': value['overage'],
        'overageCharges': value['overageCharges'],
    };
}

