/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBillingUsage200ResponseCurrentPeriod
 */
export interface GetBillingUsage200ResponseCurrentPeriod {
    /**
     * Start of the current usage period (ISO 8601)
     * @type {string}
     * @memberof GetBillingUsage200ResponseCurrentPeriod
     */
    start: string;
    /**
     * End of the current usage period (ISO 8601)
     * @type {string}
     * @memberof GetBillingUsage200ResponseCurrentPeriod
     */
    end: string;
}

/**
 * Check if a given object implements the GetBillingUsage200ResponseCurrentPeriod interface.
 */
export function instanceOfGetBillingUsage200ResponseCurrentPeriod(value: object): value is GetBillingUsage200ResponseCurrentPeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function GetBillingUsage200ResponseCurrentPeriodFromJSON(json: any): GetBillingUsage200ResponseCurrentPeriod {
    return GetBillingUsage200ResponseCurrentPeriodFromJSONTyped(json, false);
}

export function GetBillingUsage200ResponseCurrentPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingUsage200ResponseCurrentPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function GetBillingUsage200ResponseCurrentPeriodToJSON(json: any): GetBillingUsage200ResponseCurrentPeriod {
    return GetBillingUsage200ResponseCurrentPeriodToJSONTyped(json, false);
}

export function GetBillingUsage200ResponseCurrentPeriodToJSONTyped(value?: GetBillingUsage200ResponseCurrentPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

