/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBillingUsage200ResponseCurrentPeriod
 */
export interface GetBillingUsage200ResponseCurrentPeriod {
    /**
     * Start of the current usage period (ISO 8601)
     * @type {string}
     * @memberof GetBillingUsage200ResponseCurrentPeriod
     */
    start: string;
    /**
     * End of the current usage period (ISO 8601)
     * @type {string}
     * @memberof GetBillingUsage200ResponseCurrentPeriod
     */
    end: string;
}

/**
 * Check if a given object implements the GetBillingUsage200ResponseCurrentPeriod interface.
 */
export function instanceOfGetBillingUsage200ResponseCurrentPeriod(value: object): value is GetBillingUsage200ResponseCurrentPeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function GetBillingUsage200ResponseCurrentPeriodFromJSON(json: any): GetBillingUsage200ResponseCurrentPeriod {
    return GetBillingUsage200ResponseCurrentPeriodFromJSONTyped(json, false);
}

export function GetBillingUsage200ResponseCurrentPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingUsage200ResponseCurrentPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function GetBillingUsage200ResponseCurrentPeriodToJSON(json: any): GetBillingUsage200ResponseCurrentPeriod {
    return GetBillingUsage200ResponseCurrentPeriodToJSONTyped(json, false);
}

export function GetBillingUsage200ResponseCurrentPeriodToJSONTyped(value?: GetBillingUsage200ResponseCurrentPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

