/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetBillingUsage200ResponseAddOnsInner } from './GetBillingUsage200ResponseAddOnsInner';
import {
    GetBillingUsage200ResponseAddOnsInnerFromJSON,
    GetBillingUsage200ResponseAddOnsInnerFromJSONTyped,
    GetBillingUsage200ResponseAddOnsInnerToJSON,
    GetBillingUsage200ResponseAddOnsInnerToJSONTyped,
} from './GetBillingUsage200ResponseAddOnsInner';
import type { GetBillingUsage200ResponseShipments } from './GetBillingUsage200ResponseShipments';
import {
    GetBillingUsage200ResponseShipmentsFromJSON,
    GetBillingUsage200ResponseShipmentsFromJSONTyped,
    GetBillingUsage200ResponseShipmentsToJSON,
    GetBillingUsage200ResponseShipmentsToJSONTyped,
} from './GetBillingUsage200ResponseShipments';
import type { GetBillingUsage200ResponseCurrentPeriod } from './GetBillingUsage200ResponseCurrentPeriod';
import {
    GetBillingUsage200ResponseCurrentPeriodFromJSON,
    GetBillingUsage200ResponseCurrentPeriodFromJSONTyped,
    GetBillingUsage200ResponseCurrentPeriodToJSON,
    GetBillingUsage200ResponseCurrentPeriodToJSONTyped,
} from './GetBillingUsage200ResponseCurrentPeriod';
import type { GetBillingUsage200ResponseLimits } from './GetBillingUsage200ResponseLimits';
import {
    GetBillingUsage200ResponseLimitsFromJSON,
    GetBillingUsage200ResponseLimitsFromJSONTyped,
    GetBillingUsage200ResponseLimitsToJSON,
    GetBillingUsage200ResponseLimitsToJSONTyped,
} from './GetBillingUsage200ResponseLimits';

/**
 * 
 * @export
 * @interface GetBillingUsage200Response
 */
export interface GetBillingUsage200Response {
    /**
     * 
     * @type {GetBillingUsage200ResponseCurrentPeriod}
     * @memberof GetBillingUsage200Response
     */
    currentPeriod: GetBillingUsage200ResponseCurrentPeriod;
    /**
     * 
     * @type {GetBillingUsage200ResponseShipments}
     * @memberof GetBillingUsage200Response
     */
    shipments: GetBillingUsage200ResponseShipments;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimits}
     * @memberof GetBillingUsage200Response
     */
    limits: GetBillingUsage200ResponseLimits;
    /**
     * Active add-ons on the subscription
     * @type {Array<GetBillingUsage200ResponseAddOnsInner>}
     * @memberof GetBillingUsage200Response
     */
    addOns: Array<GetBillingUsage200ResponseAddOnsInner>;
}

/**
 * Check if a given object implements the GetBillingUsage200Response interface.
 */
export function instanceOfGetBillingUsage200Response(value: object): value is GetBillingUsage200Response {
    if (!('currentPeriod' in value) || value['currentPeriod'] === undefined) return false;
    if (!('shipments' in value) || value['shipments'] === undefined) return false;
    if (!('limits' in value) || value['limits'] === undefined) return false;
    if (!('addOns' in value) || value['addOns'] === undefined) return false;
    return true;
}

export function GetBillingUsage200ResponseFromJSON(json: any): GetBillingUsage200Response {
    return GetBillingUsage200ResponseFromJSONTyped(json, false);
}

export function GetBillingUsage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingUsage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPeriod': GetBillingUsage200ResponseCurrentPeriodFromJSON(json['currentPeriod']),
        'shipments': GetBillingUsage200ResponseShipmentsFromJSON(json['shipments']),
        'limits': GetBillingUsage200ResponseLimitsFromJSON(json['limits']),
        'addOns': ((json['addOns'] as Array<any>).map(GetBillingUsage200ResponseAddOnsInnerFromJSON)),
    };
}

export function GetBillingUsage200ResponseToJSON(json: any): GetBillingUsage200Response {
    return GetBillingUsage200ResponseToJSONTyped(json, false);
}

export function GetBillingUsage200ResponseToJSONTyped(value?: GetBillingUsage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentPeriod': GetBillingUsage200ResponseCurrentPeriodToJSON(value['currentPeriod']),
        'shipments': GetBillingUsage200ResponseShipmentsToJSON(value['shipments']),
        'limits': GetBillingUsage200ResponseLimitsToJSON(value['limits']),
        'addOns': ((value['addOns'] as Array<any>).map(GetBillingUsage200ResponseAddOnsInnerToJSON)),
    };
}

