/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetBillingUsage200ResponseLimitsTeamMembers } from './GetBillingUsage200ResponseLimitsTeamMembers';
import {
    GetBillingUsage200ResponseLimitsTeamMembersFromJSON,
    GetBillingUsage200ResponseLimitsTeamMembersFromJSONTyped,
    GetBillingUsage200ResponseLimitsTeamMembersToJSON,
    GetBillingUsage200ResponseLimitsTeamMembersToJSONTyped,
} from './GetBillingUsage200ResponseLimitsTeamMembers';

/**
 * 
 * @export
 * @interface GetBillingUsage200ResponseLimits
 */
export interface GetBillingUsage200ResponseLimits {
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    teamMembers: GetBillingUsage200ResponseLimitsTeamMembers;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    carriers: GetBillingUsage200ResponseLimitsTeamMembers;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    orderChannels: GetBillingUsage200ResponseLimitsTeamMembers;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    shippingRules: GetBillingUsage200ResponseLimitsTeamMembers;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    addresses: GetBillingUsage200ResponseLimitsTeamMembers;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    apiTokens: GetBillingUsage200ResponseLimitsTeamMembers;
    /**
     * 
     * @type {GetBillingUsage200ResponseLimitsTeamMembers}
     * @memberof GetBillingUsage200ResponseLimits
     */
    automations: GetBillingUsage200ResponseLimitsTeamMembers;
}

/**
 * Check if a given object implements the GetBillingUsage200ResponseLimits interface.
 */
export function instanceOfGetBillingUsage200ResponseLimits(value: object): value is GetBillingUsage200ResponseLimits {
    if (!('teamMembers' in value) || value['teamMembers'] === undefined) return false;
    if (!('carriers' in value) || value['carriers'] === undefined) return false;
    if (!('orderChannels' in value) || value['orderChannels'] === undefined) return false;
    if (!('shippingRules' in value) || value['shippingRules'] === undefined) return false;
    if (!('addresses' in value) || value['addresses'] === undefined) return false;
    if (!('apiTokens' in value) || value['apiTokens'] === undefined) return false;
    if (!('automations' in value) || value['automations'] === undefined) return false;
    return true;
}

export function GetBillingUsage200ResponseLimitsFromJSON(json: any): GetBillingUsage200ResponseLimits {
    return GetBillingUsage200ResponseLimitsFromJSONTyped(json, false);
}

export function GetBillingUsage200ResponseLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingUsage200ResponseLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'teamMembers': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['teamMembers']),
        'carriers': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['carriers']),
        'orderChannels': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['orderChannels']),
        'shippingRules': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['shippingRules']),
        'addresses': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['addresses']),
        'apiTokens': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['apiTokens']),
        'automations': GetBillingUsage200ResponseLimitsTeamMembersFromJSON(json['automations']),
    };
}

export function GetBillingUsage200ResponseLimitsToJSON(json: any): GetBillingUsage200ResponseLimits {
    return GetBillingUsage200ResponseLimitsToJSONTyped(json, false);
}

export function GetBillingUsage200ResponseLimitsToJSONTyped(value?: GetBillingUsage200ResponseLimits | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamMembers': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['teamMembers']),
        'carriers': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['carriers']),
        'orderChannels': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['orderChannels']),
        'shippingRules': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['shippingRules']),
        'addresses': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['addresses']),
        'apiTokens': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['apiTokens']),
        'automations': GetBillingUsage200ResponseLimitsTeamMembersToJSON(value['automations']),
    };
}

