/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetOrg200ResponseCount } from './GetOrg200ResponseCount';
import {
    GetOrg200ResponseCountFromJSON,
    GetOrg200ResponseCountFromJSONTyped,
    GetOrg200ResponseCountToJSON,
    GetOrg200ResponseCountToJSONTyped,
} from './GetOrg200ResponseCount';

/**
 * 
 * @export
 * @interface GetOrg200Response
 */
export interface GetOrg200Response {
    /**
     * Unique organization identifier
     * @type {string}
     * @memberof GetOrg200Response
     */
    id: string;
    /**
     * Organization name
     * @type {string}
     * @memberof GetOrg200Response
     */
    name: string;
    /**
     * Organization URL slug (unique identifier)
     * @type {string}
     * @memberof GetOrg200Response
     */
    slug: string;
    /**
     * Organization description
     * @type {string}
     * @memberof GetOrg200Response
     */
    description: string | null;
    /**
     * Billing currency (ISO 4217 code)
     * @type {string}
     * @memberof GetOrg200Response
     */
    currency: string;
    /**
     * Company VAT/tax ID for invoices
     * @type {string}
     * @memberof GetOrg200Response
     */
    vatNumber?: string | null;
    /**
     * Billing email for invoices
     * @type {string}
     * @memberof GetOrg200Response
     */
    billingEmail?: string | null;
    /**
     * Legal company name
     * @type {string}
     * @memberof GetOrg200Response
     */
    companyName?: string | null;
    /**
     * Address line 1
     * @type {string}
     * @memberof GetOrg200Response
     */
    addressLine1?: string | null;
    /**
     * Address line 2
     * @type {string}
     * @memberof GetOrg200Response
     */
    addressLine2?: string | null;
    /**
     * City
     * @type {string}
     * @memberof GetOrg200Response
     */
    city?: string | null;
    /**
     * Postal code
     * @type {string}
     * @memberof GetOrg200Response
     */
    postalCode?: string | null;
    /**
     * Country (ISO 3166-1 alpha-2 code)
     * @type {string}
     * @memberof GetOrg200Response
     */
    country?: string | null;
    /**
     * Customs identifiers keyed by type
     * @type {{ [key: string]: string; }}
     * @memberof GetOrg200Response
     */
    customs?: { [key: string]: string; } | null;
    /**
     * Creation timestamp (ISO 8601)
     * @type {string}
     * @memberof GetOrg200Response
     */
    createdAt: string;
    /**
     * Last update timestamp (ISO 8601)
     * @type {string}
     * @memberof GetOrg200Response
     */
    updatedAt: string;
    /**
     * 
     * @type {GetOrg200ResponseCount}
     * @memberof GetOrg200Response
     */
    count: GetOrg200ResponseCount;
}

/**
 * Check if a given object implements the GetOrg200Response interface.
 */
export function instanceOfGetOrg200Response(value: object): value is GetOrg200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if ((!('count' in (value as Record<string, any>)) && !('_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['count'] === undefined && (value as Record<string, any>)['_count'] === undefined)) return false;
    return true;
}

export function GetOrg200ResponseFromJSON(json: any): GetOrg200Response {
    return GetOrg200ResponseFromJSONTyped(json, false);
}

export function GetOrg200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrg200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'description': json['description'],
        'currency': json['currency'],
        'vatNumber': json['vatNumber'] === undefined ? undefined : json['vatNumber'] === null ? null : json['vatNumber'],
        'billingEmail': json['billingEmail'] === undefined ? undefined : json['billingEmail'] === null ? null : json['billingEmail'],
        'companyName': json['companyName'] === undefined ? undefined : json['companyName'] === null ? null : json['companyName'],
        'addressLine1': json['addressLine1'] === undefined ? undefined : json['addressLine1'] === null ? null : json['addressLine1'],
        'addressLine2': json['addressLine2'] === undefined ? undefined : json['addressLine2'] === null ? null : json['addressLine2'],
        'city': json['city'] === undefined ? undefined : json['city'] === null ? null : json['city'],
        'postalCode': json['postalCode'] === undefined ? undefined : json['postalCode'] === null ? null : json['postalCode'],
        'country': json['country'] === undefined ? undefined : json['country'] === null ? null : json['country'],
        'customs': json['customs'] === undefined ? undefined : json['customs'] === null ? null : json['customs'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'count': GetOrg200ResponseCountFromJSON(json['_count']),
    };
}

export function GetOrg200ResponseToJSON(json: any): GetOrg200Response {
    return GetOrg200ResponseToJSONTyped(json, false);
}

export function GetOrg200ResponseToJSONTyped(value?: GetOrg200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'description': value['description'],
        'currency': value['currency'],
        'vatNumber': value['vatNumber'],
        'billingEmail': value['billingEmail'],
        'companyName': value['companyName'],
        'addressLine1': value['addressLine1'],
        'addressLine2': value['addressLine2'],
        'city': value['city'],
        'postalCode': value['postalCode'],
        'country': value['country'],
        'customs': value['customs'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        '_count': GetOrg200ResponseCountToJSON(value['count']),
    };
}

