/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Postal address of the service point
 * @export
 * @interface ListCarrierProductServicePoints200ResponseInnerAddress
 */
export interface ListCarrierProductServicePoints200ResponseInnerAddress {
    /**
     * Street address line 1
     * @type {string}
     * @memberof ListCarrierProductServicePoints200ResponseInnerAddress
     */
    address1: string;
    /**
     * Street address line 2
     * @type {string}
     * @memberof ListCarrierProductServicePoints200ResponseInnerAddress
     */
    address2?: string | null;
    /**
     * Postal code
     * @type {string}
     * @memberof ListCarrierProductServicePoints200ResponseInnerAddress
     */
    postalCode: string;
    /**
     * State or region
     * @type {string}
     * @memberof ListCarrierProductServicePoints200ResponseInnerAddress
     */
    state?: string | null;
    /**
     * City name
     * @type {string}
     * @memberof ListCarrierProductServicePoints200ResponseInnerAddress
     */
    city: string;
    /**
     * ISO 3166-1 alpha-2 country code
     * @type {string}
     * @memberof ListCarrierProductServicePoints200ResponseInnerAddress
     */
    countryCode: string;
}

/**
 * Check if a given object implements the ListCarrierProductServicePoints200ResponseInnerAddress interface.
 */
export function instanceOfListCarrierProductServicePoints200ResponseInnerAddress(value: object): value is ListCarrierProductServicePoints200ResponseInnerAddress {
    if (!('address1' in value) || value['address1'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    return true;
}

export function ListCarrierProductServicePoints200ResponseInnerAddressFromJSON(json: any): ListCarrierProductServicePoints200ResponseInnerAddress {
    return ListCarrierProductServicePoints200ResponseInnerAddressFromJSONTyped(json, false);
}

export function ListCarrierProductServicePoints200ResponseInnerAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCarrierProductServicePoints200ResponseInnerAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'address1': json['address1'],
        'address2': json['address2'] === undefined ? undefined : json['address2'] === null ? null : json['address2'],
        'postalCode': json['postalCode'],
        'state': json['state'] === undefined ? undefined : json['state'] === null ? null : json['state'],
        'city': json['city'],
        'countryCode': json['countryCode'],
    };
}

export function ListCarrierProductServicePoints200ResponseInnerAddressToJSON(json: any): ListCarrierProductServicePoints200ResponseInnerAddress {
    return ListCarrierProductServicePoints200ResponseInnerAddressToJSONTyped(json, false);
}

export function ListCarrierProductServicePoints200ResponseInnerAddressToJSONTyped(value?: ListCarrierProductServicePoints200ResponseInnerAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address1': value['address1'],
        'address2': value['address2'],
        'postalCode': value['postalCode'],
        'state': value['state'],
        'city': value['city'],
        'countryCode': value['countryCode'],
    };
}

