/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAvailableCarriers200ResponseInnerRequiredFieldsInner } from './ListAvailableCarriers200ResponseInnerRequiredFieldsInner';
import {
    ListAvailableCarriers200ResponseInnerRequiredFieldsInnerFromJSON,
    ListAvailableCarriers200ResponseInnerRequiredFieldsInnerFromJSONTyped,
    ListAvailableCarriers200ResponseInnerRequiredFieldsInnerToJSON,
    ListAvailableCarriers200ResponseInnerRequiredFieldsInnerToJSONTyped,
} from './ListAvailableCarriers200ResponseInnerRequiredFieldsInner';

/**
 * 
 * @export
 * @interface ListAvailableCarriers200ResponseInner
 */
export interface ListAvailableCarriers200ResponseInner {
    /**
     * Display name of the carrier
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    name: string;
    /**
     * Unique carrier slug identifier
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    slug: string;
    /**
     * Carrier group or family name
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    group?: string;
    /**
     * Short description of the carrier
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    description?: string;
    /**
     * URL to the carrier logo image
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    logo?: string;
    /**
     * Carrier brand color (hex)
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    brandColor?: string;
    /**
     * URL with more information about the carrier
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    learnMoreUrl?: string;
    /**
     * Configuration fields that must be provided to connect the carrier
     * @type {Array<ListAvailableCarriers200ResponseInnerRequiredFieldsInner>}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    requiredFields?: Array<ListAvailableCarriers200ResponseInnerRequiredFieldsInner>;
    /**
     * Optional configuration fields for the carrier
     * @type {Array<ListAvailableCarriers200ResponseInnerRequiredFieldsInner>}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    optionalFields?: Array<ListAvailableCarriers200ResponseInnerRequiredFieldsInner>;
    /**
     * Whether this integration is deprecated (still works, but discouraged)
     * @type {boolean}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    deprecated?: boolean;
    /**
     * Guidance shown alongside the deprecated tag (e.g. what to migrate to)
     * @type {string}
     * @memberof ListAvailableCarriers200ResponseInner
     */
    deprecationMessage?: string;
}

/**
 * Check if a given object implements the ListAvailableCarriers200ResponseInner interface.
 */
export function instanceOfListAvailableCarriers200ResponseInner(value: object): value is ListAvailableCarriers200ResponseInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function ListAvailableCarriers200ResponseInnerFromJSON(json: any): ListAvailableCarriers200ResponseInner {
    return ListAvailableCarriers200ResponseInnerFromJSONTyped(json, false);
}

export function ListAvailableCarriers200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAvailableCarriers200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'],
        'group': json['group'] == null ? undefined : json['group'],
        'description': json['description'] == null ? undefined : json['description'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'brandColor': json['brandColor'] == null ? undefined : json['brandColor'],
        'learnMoreUrl': json['learnMoreUrl'] == null ? undefined : json['learnMoreUrl'],
        'requiredFields': json['requiredFields'] == null ? undefined : ((json['requiredFields'] as Array<any>).map(ListAvailableCarriers200ResponseInnerRequiredFieldsInnerFromJSON)),
        'optionalFields': json['optionalFields'] == null ? undefined : ((json['optionalFields'] as Array<any>).map(ListAvailableCarriers200ResponseInnerRequiredFieldsInnerFromJSON)),
        'deprecated': json['deprecated'] == null ? undefined : json['deprecated'],
        'deprecationMessage': json['deprecationMessage'] == null ? undefined : json['deprecationMessage'],
    };
}

export function ListAvailableCarriers200ResponseInnerToJSON(json: any): ListAvailableCarriers200ResponseInner {
    return ListAvailableCarriers200ResponseInnerToJSONTyped(json, false);
}

export function ListAvailableCarriers200ResponseInnerToJSONTyped(value?: ListAvailableCarriers200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
        'group': value['group'],
        'description': value['description'],
        'logo': value['logo'],
        'brandColor': value['brandColor'],
        'learnMoreUrl': value['learnMoreUrl'],
        'requiredFields': value['requiredFields'] == null ? undefined : ((value['requiredFields'] as Array<any>).map(ListAvailableCarriers200ResponseInnerRequiredFieldsInnerToJSON)),
        'optionalFields': value['optionalFields'] == null ? undefined : ((value['optionalFields'] as Array<any>).map(ListAvailableCarriers200ResponseInnerRequiredFieldsInnerToJSON)),
        'deprecated': value['deprecated'],
        'deprecationMessage': value['deprecationMessage'],
    };
}

