/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValue } from './ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValue';
import {
    ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueFromJSON,
    ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueFromJSONTyped,
    ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueToJSON,
    ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueToJSONTyped,
} from './ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValue';

/**
 * 
 * @export
 * @interface ListShipments200ResponseDataInnerCarrierSettings
 */
export interface ListShipments200ResponseDataInnerCarrierSettings {
    /**
     * Identifier of the carrier to use.
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerCarrierSettings
     */
    carrierId: string;
    /**
     * Identifier of the carrier product/service.
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerCarrierSettings
     */
    productId: string;
    /**
     * Additional service codes requested from the carrier.
     * @type {Array<string>}
     * @memberof ListShipments200ResponseDataInnerCarrierSettings
     */
    services: Array<string>;
    /**
     * Carrier-specific extra parameters as key/value pairs.
     * @type {{ [key: string]: ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValue; }}
     * @memberof ListShipments200ResponseDataInnerCarrierSettings
     */
    additionalParameters: { [key: string]: ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValue; };
}

/**
 * Check if a given object implements the ListShipments200ResponseDataInnerCarrierSettings interface.
 */
export function instanceOfListShipments200ResponseDataInnerCarrierSettings(value: object): value is ListShipments200ResponseDataInnerCarrierSettings {
    if (!('carrierId' in value) || value['carrierId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    if (!('additionalParameters' in value) || value['additionalParameters'] === undefined) return false;
    return true;
}

export function ListShipments200ResponseDataInnerCarrierSettingsFromJSON(json: any): ListShipments200ResponseDataInnerCarrierSettings {
    return ListShipments200ResponseDataInnerCarrierSettingsFromJSONTyped(json, false);
}

export function ListShipments200ResponseDataInnerCarrierSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShipments200ResponseDataInnerCarrierSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'carrierId': json['carrierId'],
        'productId': json['productId'],
        'services': json['services'],
        'additionalParameters': (mapValues(json['additionalParameters'], ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueFromJSON)),
    };
}

export function ListShipments200ResponseDataInnerCarrierSettingsToJSON(json: any): ListShipments200ResponseDataInnerCarrierSettings {
    return ListShipments200ResponseDataInnerCarrierSettingsToJSONTyped(json, false);
}

export function ListShipments200ResponseDataInnerCarrierSettingsToJSONTyped(value?: ListShipments200ResponseDataInnerCarrierSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrierId': value['carrierId'],
        'productId': value['productId'],
        'services': value['services'],
        'additionalParameters': (mapValues(value['additionalParameters'], ListShipments200ResponseDataInnerCarrierSettingsAdditionalParametersValueToJSON)),
    };
}

