/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListShipments200ResponseDataInnerAddress
 */
export interface ListShipments200ResponseDataInnerAddress {
    /**
     * Unique address identifier
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    id: string;
    /**
     * Name of the address
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    name: string;
    /**
     * Attention contact person
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    attContact: string;
    /**
     * Address line 1
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    address1: string;
    /**
     * Address line 2
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    address2: string | null;
    /**
     * Postal/ZIP code
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    zipcode: string;
    /**
     * City
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    city: string;
    /**
     * Phone number
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    phone: string;
    /**
     * ISO country code
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    countryCode: string;
    /**
     * State/Province
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    state: string | null;
    /**
     * Email address
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    email: string;
    /**
     * Customs identifiers keyed by type
     * @type {{ [key: string]: string; }}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    customs?: { [key: string]: string; } | null;
    /**
     * Address types (sender, pickup, return)
     * @type {Array<ListShipments200ResponseDataInnerAddressAddressTypesEnum>}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    addressTypes: Array<ListShipments200ResponseDataInnerAddressAddressTypesEnum>;
    /**
     * Owning organization ID
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    orgId: string;
    /**
     * Creation timestamp (ISO 8601)
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    createdAt: string;
    /**
     * Last update timestamp (ISO 8601)
     * @type {string}
     * @memberof ListShipments200ResponseDataInnerAddress
     */
    updatedAt: string;
}


/**
 * @export
 */
export const ListShipments200ResponseDataInnerAddressAddressTypesEnum = {
    Sender: 'sender',
    Pickup: 'pickup',
    Return: 'return'
} as const;
export type ListShipments200ResponseDataInnerAddressAddressTypesEnum = typeof ListShipments200ResponseDataInnerAddressAddressTypesEnum[keyof typeof ListShipments200ResponseDataInnerAddressAddressTypesEnum];


/**
 * Check if a given object implements the ListShipments200ResponseDataInnerAddress interface.
 */
export function instanceOfListShipments200ResponseDataInnerAddress(value: object): value is ListShipments200ResponseDataInnerAddress {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('attContact' in value) || value['attContact'] === undefined) return false;
    if (!('address1' in value) || value['address1'] === undefined) return false;
    if (!('address2' in value) || value['address2'] === undefined) return false;
    if (!('zipcode' in value) || value['zipcode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('addressTypes' in value) || value['addressTypes'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ListShipments200ResponseDataInnerAddressFromJSON(json: any): ListShipments200ResponseDataInnerAddress {
    return ListShipments200ResponseDataInnerAddressFromJSONTyped(json, false);
}

export function ListShipments200ResponseDataInnerAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShipments200ResponseDataInnerAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'attContact': json['attContact'],
        'address1': json['address1'],
        'address2': json['address2'],
        'zipcode': json['zipcode'],
        'city': json['city'],
        'phone': json['phone'],
        'countryCode': json['countryCode'],
        'state': json['state'],
        'email': json['email'],
        'customs': json['customs'] === undefined ? undefined : json['customs'] === null ? null : json['customs'],
        'addressTypes': json['addressTypes'],
        'orgId': json['orgId'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function ListShipments200ResponseDataInnerAddressToJSON(json: any): ListShipments200ResponseDataInnerAddress {
    return ListShipments200ResponseDataInnerAddressToJSONTyped(json, false);
}

export function ListShipments200ResponseDataInnerAddressToJSONTyped(value?: ListShipments200ResponseDataInnerAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'attContact': value['attContact'],
        'address1': value['address1'],
        'address2': value['address2'],
        'zipcode': value['zipcode'],
        'city': value['city'],
        'phone': value['phone'],
        'countryCode': value['countryCode'],
        'state': value['state'],
        'email': value['email'],
        'customs': value['customs'],
        'addressTypes': value['addressTypes'],
        'orgId': value['orgId'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

