/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListShippingRules200ResponseDataInnerConditionsInnerOneOf } from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf';
import {
    instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOfFromJSON,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOfFromJSONTyped,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOfToJSON,
} from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf';
import type { ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 } from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf1';
import {
    instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf1,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf1FromJSON,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf1FromJSONTyped,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf1ToJSON,
} from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf1';
import type { ListShippingRules200ResponseDataInnerConditionsInnerOneOf2 } from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf2';
import {
    instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf2,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf2FromJSON,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf2FromJSONTyped,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf2ToJSON,
} from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf2';
import type { ListShippingRules200ResponseDataInnerConditionsInnerOneOf3 } from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf3';
import {
    instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf3,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf3FromJSON,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf3FromJSONTyped,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf3ToJSON,
} from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf3';
import type { ListShippingRules200ResponseDataInnerConditionsInnerOneOf4 } from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf4';
import {
    instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf4,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf4FromJSON,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf4FromJSONTyped,
    ListShippingRules200ResponseDataInnerConditionsInnerOneOf4ToJSON,
} from './ListShippingRules200ResponseDataInnerConditionsInnerOneOf4';

/**
 * @type ListShippingRules200ResponseDataInnerConditionsInner
 * 
 * @export
 */
export type ListShippingRules200ResponseDataInnerConditionsInner = ListShippingRules200ResponseDataInnerConditionsInnerOneOf | ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 | ListShippingRules200ResponseDataInnerConditionsInnerOneOf2 | ListShippingRules200ResponseDataInnerConditionsInnerOneOf3 | ListShippingRules200ResponseDataInnerConditionsInnerOneOf4;

export function ListShippingRules200ResponseDataInnerConditionsInnerFromJSON(json: any): ListShippingRules200ResponseDataInnerConditionsInner {
    return ListShippingRules200ResponseDataInnerConditionsInnerFromJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShippingRules200ResponseDataInnerConditionsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf(json)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOfFromJSONTyped(json, true);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf1(json)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf2(json)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf2FromJSONTyped(json, true);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf3(json)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf3FromJSONTyped(json, true);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf4(json)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf4FromJSONTyped(json, true);
    }
    return {} as any;
}

export function ListShippingRules200ResponseDataInnerConditionsInnerToJSON(json: any): any {
    return ListShippingRules200ResponseDataInnerConditionsInnerToJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerConditionsInnerToJSONTyped(value?: ListShippingRules200ResponseDataInnerConditionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf(value)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOfToJSON(value as ListShippingRules200ResponseDataInnerConditionsInnerOneOf);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf1(value)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf1ToJSON(value as ListShippingRules200ResponseDataInnerConditionsInnerOneOf1);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf2(value)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf2ToJSON(value as ListShippingRules200ResponseDataInnerConditionsInnerOneOf2);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf3(value)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf3ToJSON(value as ListShippingRules200ResponseDataInnerConditionsInnerOneOf3);
    }
    if (instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf4(value)) {
        return ListShippingRules200ResponseDataInnerConditionsInnerOneOf4ToJSON(value as ListShippingRules200ResponseDataInnerConditionsInnerOneOf4);
    }
    return {};
}

