/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListShippingRules200ResponseDataInnerReturnShippingRule
 */
export interface ListShippingRules200ResponseDataInnerReturnShippingRule {
    /**
     * Return shipping rule ID
     * @type {string}
     * @memberof ListShippingRules200ResponseDataInnerReturnShippingRule
     */
    id: string;
    /**
     * Return shipping rule name
     * @type {string}
     * @memberof ListShippingRules200ResponseDataInnerReturnShippingRule
     */
    name: string;
}

/**
 * Check if a given object implements the ListShippingRules200ResponseDataInnerReturnShippingRule interface.
 */
export function instanceOfListShippingRules200ResponseDataInnerReturnShippingRule(value: object): value is ListShippingRules200ResponseDataInnerReturnShippingRule {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ListShippingRules200ResponseDataInnerReturnShippingRuleFromJSON(json: any): ListShippingRules200ResponseDataInnerReturnShippingRule {
    return ListShippingRules200ResponseDataInnerReturnShippingRuleFromJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerReturnShippingRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShippingRules200ResponseDataInnerReturnShippingRule {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ListShippingRules200ResponseDataInnerReturnShippingRuleToJSON(json: any): ListShippingRules200ResponseDataInnerReturnShippingRule {
    return ListShippingRules200ResponseDataInnerReturnShippingRuleToJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerReturnShippingRuleToJSONTyped(value?: ListShippingRules200ResponseDataInnerReturnShippingRule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

