/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
 */
export interface ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 {
    /**
     * Condition type discriminator
     * @type {ListShippingRules200ResponseDataInnerConditionsInnerOneOf1TypeEnum}
     * @memberof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
     */
    type: ListShippingRules200ResponseDataInnerConditionsInnerOneOf1TypeEnum;
    /**
     * Whether to compare against subtotal (before discounts) or total (after discounts)
     * @type {ListShippingRules200ResponseDataInnerConditionsInnerOneOf1PriceTypeEnum}
     * @memberof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
     */
    priceType: ListShippingRules200ResponseDataInnerConditionsInnerOneOf1PriceTypeEnum;
    /**
     * Comparison operator
     * @type {ListShippingRules200ResponseDataInnerConditionsInnerOneOf1OperatorEnum}
     * @memberof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
     */
    operator: ListShippingRules200ResponseDataInnerConditionsInnerOneOf1OperatorEnum;
    /**
     * Price value to compare against
     * @type {number}
     * @memberof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
     */
    value: number;
    /**
     * Shipping price when condition matches
     * @type {number}
     * @memberof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
     */
    shippingPrice: number;
    /**
     * ISO 4217 currency code
     * @type {string}
     * @memberof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1
     */
    currency: string;
}


/**
 * @export
 */
export const ListShippingRules200ResponseDataInnerConditionsInnerOneOf1TypeEnum = {
    Price: 'price'
} as const;
export type ListShippingRules200ResponseDataInnerConditionsInnerOneOf1TypeEnum = typeof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1TypeEnum[keyof typeof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1TypeEnum];

/**
 * @export
 */
export const ListShippingRules200ResponseDataInnerConditionsInnerOneOf1PriceTypeEnum = {
    Subtotal: 'subtotal',
    Total: 'total'
} as const;
export type ListShippingRules200ResponseDataInnerConditionsInnerOneOf1PriceTypeEnum = typeof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1PriceTypeEnum[keyof typeof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1PriceTypeEnum];

/**
 * @export
 */
export const ListShippingRules200ResponseDataInnerConditionsInnerOneOf1OperatorEnum = {
    Gt: 'gt',
    Gte: 'gte',
    Lt: 'lt',
    Lte: 'lte',
    Eq: 'eq'
} as const;
export type ListShippingRules200ResponseDataInnerConditionsInnerOneOf1OperatorEnum = typeof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1OperatorEnum[keyof typeof ListShippingRules200ResponseDataInnerConditionsInnerOneOf1OperatorEnum];


/**
 * Check if a given object implements the ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 interface.
 */
export function instanceOfListShippingRules200ResponseDataInnerConditionsInnerOneOf1(value: object): value is ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'price') return false;
    
    if (!('priceType' in value) || value['priceType'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('shippingPrice' in value) || value['shippingPrice'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function ListShippingRules200ResponseDataInnerConditionsInnerOneOf1FromJSON(json: any): ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 {
    return ListShippingRules200ResponseDataInnerConditionsInnerOneOf1FromJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerConditionsInnerOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'priceType': json['priceType'],
        'operator': json['operator'],
        'value': json['value'],
        'shippingPrice': json['shippingPrice'],
        'currency': json['currency'],
    };
}

export function ListShippingRules200ResponseDataInnerConditionsInnerOneOf1ToJSON(json: any): ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 {
    return ListShippingRules200ResponseDataInnerConditionsInnerOneOf1ToJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerConditionsInnerOneOf1ToJSONTyped(value?: ListShippingRules200ResponseDataInnerConditionsInnerOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'priceType': value['priceType'],
        'operator': value['operator'],
        'value': value['value'],
        'shippingPrice': value['shippingPrice'],
        'currency': value['currency'],
    };
}

