/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListOrders200ResponseDataInnerOrderChannel } from './ListOrders200ResponseDataInnerOrderChannel';
import {
    ListOrders200ResponseDataInnerOrderChannelFromJSON,
    ListOrders200ResponseDataInnerOrderChannelFromJSONTyped,
    ListOrders200ResponseDataInnerOrderChannelToJSON,
    ListOrders200ResponseDataInnerOrderChannelToJSONTyped,
} from './ListOrders200ResponseDataInnerOrderChannel';

/**
 * 
 * @export
 * @interface ListOrders200ResponseDataInner
 */
export interface ListOrders200ResponseDataInner {
    /**
     * Unique order ID.
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    id: string;
    /**
     * Human-readable order number.
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    orderNumber: string;
    /**
     * Customer full name.
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    customerName?: string | null;
    /**
     * Customer email address.
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    customerEmail?: string | null;
    /**
     * Order fulfilment status derived from its shipments.
     * @type {ListOrders200ResponseDataInnerStatusEnum}
     * @memberof ListOrders200ResponseDataInner
     */
    status: ListOrders200ResponseDataInnerStatusEnum;
    /**
     * Order subtotal before shipping and tax.
     * @type {number}
     * @memberof ListOrders200ResponseDataInner
     */
    subtotalAmount?: number | null;
    /**
     * Order grand total.
     * @type {number}
     * @memberof ListOrders200ResponseDataInner
     */
    totalAmount?: number | null;
    /**
     * ISO 4217 currency code.
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    currency?: string | null;
    /**
     * Number of shipments created for the order.
     * @type {number}
     * @memberof ListOrders200ResponseDataInner
     */
    shipmentCount: number;
    /**
     * 
     * @type {ListOrders200ResponseDataInnerOrderChannel}
     * @memberof ListOrders200ResponseDataInner
     */
    orderChannel: ListOrders200ResponseDataInnerOrderChannel;
    /**
     * Creation timestamp (ISO 8601).
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    createdAt: string;
    /**
     * Last update timestamp (ISO 8601).
     * @type {string}
     * @memberof ListOrders200ResponseDataInner
     */
    updatedAt: string;
}


/**
 * @export
 */
export const ListOrders200ResponseDataInnerStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    PartiallyFulfilled: 'partially_fulfilled',
    Fulfilled: 'fulfilled',
    Error: 'error',
    Cancelled: 'cancelled'
} as const;
export type ListOrders200ResponseDataInnerStatusEnum = typeof ListOrders200ResponseDataInnerStatusEnum[keyof typeof ListOrders200ResponseDataInnerStatusEnum];


/**
 * Check if a given object implements the ListOrders200ResponseDataInner interface.
 */
export function instanceOfListOrders200ResponseDataInner(value: object): value is ListOrders200ResponseDataInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('orderNumber' in value) || value['orderNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('shipmentCount' in value) || value['shipmentCount'] === undefined) return false;
    if (!('orderChannel' in value) || value['orderChannel'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ListOrders200ResponseDataInnerFromJSON(json: any): ListOrders200ResponseDataInner {
    return ListOrders200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListOrders200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrders200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orderNumber': json['orderNumber'],
        'customerName': json['customerName'] === undefined ? undefined : json['customerName'] === null ? null : json['customerName'],
        'customerEmail': json['customerEmail'] === undefined ? undefined : json['customerEmail'] === null ? null : json['customerEmail'],
        'status': json['status'],
        'subtotalAmount': json['subtotalAmount'] === undefined ? undefined : json['subtotalAmount'] === null ? null : json['subtotalAmount'],
        'totalAmount': json['totalAmount'] === undefined ? undefined : json['totalAmount'] === null ? null : json['totalAmount'],
        'currency': json['currency'] === undefined ? undefined : json['currency'] === null ? null : json['currency'],
        'shipmentCount': json['shipmentCount'],
        'orderChannel': ListOrders200ResponseDataInnerOrderChannelFromJSON(json['orderChannel']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function ListOrders200ResponseDataInnerToJSON(json: any): ListOrders200ResponseDataInner {
    return ListOrders200ResponseDataInnerToJSONTyped(json, false);
}

export function ListOrders200ResponseDataInnerToJSONTyped(value?: ListOrders200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orderNumber': value['orderNumber'],
        'customerName': value['customerName'],
        'customerEmail': value['customerEmail'],
        'status': value['status'],
        'subtotalAmount': value['subtotalAmount'],
        'totalAmount': value['totalAmount'],
        'currency': value['currency'],
        'shipmentCount': value['shipmentCount'],
        'orderChannel': ListOrders200ResponseDataInnerOrderChannelToJSON(value['orderChannel']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

