/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListOrgWebhookDeliveries200ResponseDataInner } from './ListOrgWebhookDeliveries200ResponseDataInner';
import {
    ListOrgWebhookDeliveries200ResponseDataInnerFromJSON,
    ListOrgWebhookDeliveries200ResponseDataInnerFromJSONTyped,
    ListOrgWebhookDeliveries200ResponseDataInnerToJSON,
    ListOrgWebhookDeliveries200ResponseDataInnerToJSONTyped,
} from './ListOrgWebhookDeliveries200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListOrgWebhookDeliveries200Response
 */
export interface ListOrgWebhookDeliveries200Response {
    /**
     * Page of results
     * @type {Array<ListOrgWebhookDeliveries200ResponseDataInner>}
     * @memberof ListOrgWebhookDeliveries200Response
     */
    data: Array<ListOrgWebhookDeliveries200ResponseDataInner>;
    /**
     * Total matching items across all pages
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200Response
     */
    total: number;
    /**
     * Current page number (1-based)
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200Response
     */
    page: number;
    /**
     * Items per page
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200Response
     */
    limit: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200Response
     */
    totalPages: number;
}

/**
 * Check if a given object implements the ListOrgWebhookDeliveries200Response interface.
 */
export function instanceOfListOrgWebhookDeliveries200Response(value: object): value is ListOrgWebhookDeliveries200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function ListOrgWebhookDeliveries200ResponseFromJSON(json: any): ListOrgWebhookDeliveries200Response {
    return ListOrgWebhookDeliveries200ResponseFromJSONTyped(json, false);
}

export function ListOrgWebhookDeliveries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrgWebhookDeliveries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ListOrgWebhookDeliveries200ResponseDataInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
        'totalPages': json['totalPages'],
    };
}

export function ListOrgWebhookDeliveries200ResponseToJSON(json: any): ListOrgWebhookDeliveries200Response {
    return ListOrgWebhookDeliveries200ResponseToJSONTyped(json, false);
}

export function ListOrgWebhookDeliveries200ResponseToJSONTyped(value?: ListOrgWebhookDeliveries200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ListOrgWebhookDeliveries200ResponseDataInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
        'totalPages': value['totalPages'],
    };
}

