/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner } from './ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner';
import {
    ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInnerFromJSON,
    ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInnerFromJSONTyped,
    ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInnerToJSON,
    ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInnerToJSONTyped,
} from './ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner';

/**
 * 
 * @export
 * @interface ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf
 */
export interface ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf {
    /**
     * Identifier of the selected service point.
     * @type {string}
     * @memberof ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf
     */
    id: string;
    /**
     * Display name of the service point.
     * @type {string}
     * @memberof ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf
     */
    name: string;
    /**
     * Formatted address of the service point.
     * @type {string}
     * @memberof ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf
     */
    address: string;
    /**
     * Latitude/longitude of the service point.
     * @type {Array<ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner>}
     * @memberof ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf
     */
    coordinates?: Array<ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInner>;
}

/**
 * Check if a given object implements the ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf interface.
 */
export function instanceOfListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf(value: object): value is ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfFromJSON(json: any): ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf {
    return ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfFromJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'address': json['address'],
        'coordinates': json['coordinates'] == null ? undefined : ((json['coordinates'] as Array<any>).map(ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInnerFromJSON)),
    };
}

export function ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfToJSON(json: any): ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf {
    return ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfToJSONTyped(json, false);
}

export function ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfToJSONTyped(value?: ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'address': value['address'],
        'coordinates': value['coordinates'] == null ? undefined : ((value['coordinates'] as Array<any>).map(ListShippingRules200ResponseDataInnerAdditionalParametersValueAnyOfCoordinatesInnerToJSON)),
    };
}

