/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListOrgWebhooks200ResponseDataInner } from './ListOrgWebhooks200ResponseDataInner';
import {
    ListOrgWebhooks200ResponseDataInnerFromJSON,
    ListOrgWebhooks200ResponseDataInnerFromJSONTyped,
    ListOrgWebhooks200ResponseDataInnerToJSON,
    ListOrgWebhooks200ResponseDataInnerToJSONTyped,
} from './ListOrgWebhooks200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListOrgWebhooks200Response
 */
export interface ListOrgWebhooks200Response {
    /**
     * Page of results
     * @type {Array<ListOrgWebhooks200ResponseDataInner>}
     * @memberof ListOrgWebhooks200Response
     */
    data: Array<ListOrgWebhooks200ResponseDataInner>;
    /**
     * Total matching items across all pages
     * @type {number}
     * @memberof ListOrgWebhooks200Response
     */
    total: number;
    /**
     * Current page number (1-based)
     * @type {number}
     * @memberof ListOrgWebhooks200Response
     */
    page: number;
    /**
     * Items per page
     * @type {number}
     * @memberof ListOrgWebhooks200Response
     */
    limit: number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof ListOrgWebhooks200Response
     */
    totalPages: number;
}

/**
 * Check if a given object implements the ListOrgWebhooks200Response interface.
 */
export function instanceOfListOrgWebhooks200Response(value: object): value is ListOrgWebhooks200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function ListOrgWebhooks200ResponseFromJSON(json: any): ListOrgWebhooks200Response {
    return ListOrgWebhooks200ResponseFromJSONTyped(json, false);
}

export function ListOrgWebhooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrgWebhooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ListOrgWebhooks200ResponseDataInnerFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
        'totalPages': json['totalPages'],
    };
}

export function ListOrgWebhooks200ResponseToJSON(json: any): ListOrgWebhooks200Response {
    return ListOrgWebhooks200ResponseToJSONTyped(json, false);
}

export function ListOrgWebhooks200ResponseToJSONTyped(value?: ListOrgWebhooks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ListOrgWebhooks200ResponseDataInnerToJSON)),
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
        'totalPages': value['totalPages'],
    };
}

