/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListCarrierProducts200ResponseInnerAdditionalParametersInner } from './ListCarrierProducts200ResponseInnerAdditionalParametersInner';
import {
    ListCarrierProducts200ResponseInnerAdditionalParametersInnerFromJSON,
    ListCarrierProducts200ResponseInnerAdditionalParametersInnerFromJSONTyped,
    ListCarrierProducts200ResponseInnerAdditionalParametersInnerToJSON,
    ListCarrierProducts200ResponseInnerAdditionalParametersInnerToJSONTyped,
} from './ListCarrierProducts200ResponseInnerAdditionalParametersInner';
import type { ListCarrierProducts200ResponseInnerWeightLimits } from './ListCarrierProducts200ResponseInnerWeightLimits';
import {
    ListCarrierProducts200ResponseInnerWeightLimitsFromJSON,
    ListCarrierProducts200ResponseInnerWeightLimitsFromJSONTyped,
    ListCarrierProducts200ResponseInnerWeightLimitsToJSON,
    ListCarrierProducts200ResponseInnerWeightLimitsToJSONTyped,
} from './ListCarrierProducts200ResponseInnerWeightLimits';
import type { ListCarrierProducts200ResponseInnerServicesInner } from './ListCarrierProducts200ResponseInnerServicesInner';
import {
    ListCarrierProducts200ResponseInnerServicesInnerFromJSON,
    ListCarrierProducts200ResponseInnerServicesInnerFromJSONTyped,
    ListCarrierProducts200ResponseInnerServicesInnerToJSON,
    ListCarrierProducts200ResponseInnerServicesInnerToJSONTyped,
} from './ListCarrierProducts200ResponseInnerServicesInner';

/**
 * 
 * @export
 * @interface ListCarrierProducts200ResponseInner
 */
export interface ListCarrierProducts200ResponseInner {
    /**
     * Display name of the shipping product
     * @type {string}
     * @memberof ListCarrierProducts200ResponseInner
     */
    name: string;
    /**
     * Unique carrier product identifier
     * @type {string}
     * @memberof ListCarrierProducts200ResponseInner
     */
    productId: string;
    /**
     * Direction of the shipment for this product
     * @type {ListCarrierProducts200ResponseInnerTypeEnum}
     * @memberof ListCarrierProducts200ResponseInner
     */
    type: ListCarrierProducts200ResponseInnerTypeEnum;
    /**
     * Description of the shipping product
     * @type {string}
     * @memberof ListCarrierProducts200ResponseInner
     */
    description?: string;
    /**
     * Recipient countries supported by this product
     * @type {Array<string>}
     * @memberof ListCarrierProducts200ResponseInner
     */
    availableCountries: Array<string>;
    /**
     * Sender countries supported by this product
     * @type {Array<string>}
     * @memberof ListCarrierProducts200ResponseInner
     */
    availableSenderCountries: Array<string>;
    /**
     * Whether delivery is to a service point/pickup location
     * @type {boolean}
     * @memberof ListCarrierProducts200ResponseInner
     */
    isServicePoint: boolean;
    /**
     * Whether carrier pickup is available for this product
     * @type {boolean}
     * @memberof ListCarrierProducts200ResponseInner
     */
    isPickupAvailable: boolean;
    /**
     * Additional services available for this product
     * @type {Array<ListCarrierProducts200ResponseInnerServicesInner>}
     * @memberof ListCarrierProducts200ResponseInner
     */
    services?: Array<ListCarrierProducts200ResponseInnerServicesInner>;
    /**
     * Extra parameters that can or must be supplied for this product
     * @type {Array<ListCarrierProducts200ResponseInnerAdditionalParametersInner>}
     * @memberof ListCarrierProducts200ResponseInner
     */
    additionalParameters?: Array<ListCarrierProducts200ResponseInnerAdditionalParametersInner>;
    /**
     * 
     * @type {ListCarrierProducts200ResponseInnerWeightLimits}
     * @memberof ListCarrierProducts200ResponseInner
     */
    weightLimits?: ListCarrierProducts200ResponseInnerWeightLimits;
}


/**
 * @export
 */
export const ListCarrierProducts200ResponseInnerTypeEnum = {
    Outbound: 'outbound',
    Inbound: 'inbound'
} as const;
export type ListCarrierProducts200ResponseInnerTypeEnum = typeof ListCarrierProducts200ResponseInnerTypeEnum[keyof typeof ListCarrierProducts200ResponseInnerTypeEnum];


/**
 * Check if a given object implements the ListCarrierProducts200ResponseInner interface.
 */
export function instanceOfListCarrierProducts200ResponseInner(value: object): value is ListCarrierProducts200ResponseInner {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('availableCountries' in value) || value['availableCountries'] === undefined) return false;
    if (!('availableSenderCountries' in value) || value['availableSenderCountries'] === undefined) return false;
    if (!('isServicePoint' in value) || value['isServicePoint'] === undefined) return false;
    if (!('isPickupAvailable' in value) || value['isPickupAvailable'] === undefined) return false;
    return true;
}

export function ListCarrierProducts200ResponseInnerFromJSON(json: any): ListCarrierProducts200ResponseInner {
    return ListCarrierProducts200ResponseInnerFromJSONTyped(json, false);
}

export function ListCarrierProducts200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCarrierProducts200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'productId': json['productId'],
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'availableCountries': json['availableCountries'],
        'availableSenderCountries': json['availableSenderCountries'],
        'isServicePoint': json['isServicePoint'],
        'isPickupAvailable': json['isPickupAvailable'],
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(ListCarrierProducts200ResponseInnerServicesInnerFromJSON)),
        'additionalParameters': json['additionalParameters'] == null ? undefined : ((json['additionalParameters'] as Array<any>).map(ListCarrierProducts200ResponseInnerAdditionalParametersInnerFromJSON)),
        'weightLimits': json['weightLimits'] == null ? undefined : ListCarrierProducts200ResponseInnerWeightLimitsFromJSON(json['weightLimits']),
    };
}

export function ListCarrierProducts200ResponseInnerToJSON(json: any): ListCarrierProducts200ResponseInner {
    return ListCarrierProducts200ResponseInnerToJSONTyped(json, false);
}

export function ListCarrierProducts200ResponseInnerToJSONTyped(value?: ListCarrierProducts200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'productId': value['productId'],
        'type': value['type'],
        'description': value['description'],
        'availableCountries': value['availableCountries'],
        'availableSenderCountries': value['availableSenderCountries'],
        'isServicePoint': value['isServicePoint'],
        'isPickupAvailable': value['isPickupAvailable'],
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(ListCarrierProducts200ResponseInnerServicesInnerToJSON)),
        'additionalParameters': value['additionalParameters'] == null ? undefined : ((value['additionalParameters'] as Array<any>).map(ListCarrierProducts200ResponseInnerAdditionalParametersInnerToJSON)),
        'weightLimits': ListCarrierProducts200ResponseInnerWeightLimitsToJSON(value['weightLimits']),
    };
}

