/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListOrgWebhookDeliveries200ResponseDataInner
 */
export interface ListOrgWebhookDeliveries200ResponseDataInner {
    /**
     * Delivery log ID
     * @type {string}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    id: string;
    /**
     * ID of the webhook this delivery belongs to
     * @type {string}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    webhookId: string;
    /**
     * Event type that was delivered
     * @type {string}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    event: string;
    /**
     * JSON payload that was sent
     * @type {any}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    payload: any | null;
    /**
     * HTTP status code returned by the endpoint
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    statusCode: number | null;
    /**
     * Response body returned by the endpoint
     * @type {string}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    response: string | null;
    /**
     * Request duration in milliseconds
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    duration: number | null;
    /**
     * Whether the delivery succeeded
     * @type {boolean}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    success: boolean;
    /**
     * Delivery attempt number
     * @type {number}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    attempt: number;
    /**
     * Error message if the delivery failed
     * @type {string}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    error: string | null;
    /**
     * Delivery timestamp (ISO 8601)
     * @type {string}
     * @memberof ListOrgWebhookDeliveries200ResponseDataInner
     */
    createdAt: string;
}

/**
 * Check if a given object implements the ListOrgWebhookDeliveries200ResponseDataInner interface.
 */
export function instanceOfListOrgWebhookDeliveries200ResponseDataInner(value: object): value is ListOrgWebhookDeliveries200ResponseDataInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('webhookId' in value) || value['webhookId'] === undefined) return false;
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ListOrgWebhookDeliveries200ResponseDataInnerFromJSON(json: any): ListOrgWebhookDeliveries200ResponseDataInner {
    return ListOrgWebhookDeliveries200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListOrgWebhookDeliveries200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrgWebhookDeliveries200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'webhookId': json['webhookId'],
        'event': json['event'],
        'payload': json['payload'],
        'statusCode': json['statusCode'],
        'response': json['response'],
        'duration': json['duration'],
        'success': json['success'],
        'attempt': json['attempt'],
        'error': json['error'],
        'createdAt': json['createdAt'],
    };
}

export function ListOrgWebhookDeliveries200ResponseDataInnerToJSON(json: any): ListOrgWebhookDeliveries200ResponseDataInner {
    return ListOrgWebhookDeliveries200ResponseDataInnerToJSONTyped(json, false);
}

export function ListOrgWebhookDeliveries200ResponseDataInnerToJSONTyped(value?: ListOrgWebhookDeliveries200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'webhookId': value['webhookId'],
        'event': value['event'],
        'payload': value['payload'],
        'statusCode': value['statusCode'],
        'response': value['response'],
        'duration': value['duration'],
        'success': value['success'],
        'attempt': value['attempt'],
        'error': value['error'],
        'createdAt': value['createdAt'],
    };
}

