/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackShipment200ResponseEventsInner } from './TrackShipment200ResponseEventsInner';
import {
    TrackShipment200ResponseEventsInnerFromJSON,
    TrackShipment200ResponseEventsInnerFromJSONTyped,
    TrackShipment200ResponseEventsInnerToJSON,
    TrackShipment200ResponseEventsInnerToJSONTyped,
} from './TrackShipment200ResponseEventsInner';

/**
 * 
 * @export
 * @interface TrackShipment200Response
 */
export interface TrackShipment200Response {
    /**
     * Carrier tracking number.
     * @type {string}
     * @memberof TrackShipment200Response
     */
    trackingNumber: string | null;
    /**
     * Public carrier tracking URL.
     * @type {string}
     * @memberof TrackShipment200Response
     */
    trackingUrl: string | null;
    /**
     * Latest normalized tracking status.
     * @type {TrackShipment200ResponseCurrentStatusEnum}
     * @memberof TrackShipment200Response
     */
    currentStatus: TrackShipment200ResponseCurrentStatusEnum | null;
    /**
     * Estimated delivery timestamp.
     * @type {string}
     * @memberof TrackShipment200Response
     */
    estimatedDelivery?: string | null;
    /**
     * Tracking events ordered from newest to oldest.
     * @type {Array<TrackShipment200ResponseEventsInner>}
     * @memberof TrackShipment200Response
     */
    events: Array<TrackShipment200ResponseEventsInner>;
}


/**
 * @export
 */
export const TrackShipment200ResponseCurrentStatusEnum = {
    Created: 'created',
    AwaitingPickup: 'awaiting_pickup',
    PickedUp: 'picked_up',
    InTransit: 'in_transit',
    OutForDelivery: 'out_for_delivery',
    ReadyForPickup: 'ready_for_pickup',
    Delivered: 'delivered',
    Returned: 'returned',
    Exception: 'exception'
} as const;
export type TrackShipment200ResponseCurrentStatusEnum = typeof TrackShipment200ResponseCurrentStatusEnum[keyof typeof TrackShipment200ResponseCurrentStatusEnum];


/**
 * Check if a given object implements the TrackShipment200Response interface.
 */
export function instanceOfTrackShipment200Response(value: object): value is TrackShipment200Response {
    if (!('trackingNumber' in value) || value['trackingNumber'] === undefined) return false;
    if (!('trackingUrl' in value) || value['trackingUrl'] === undefined) return false;
    if (!('currentStatus' in value) || value['currentStatus'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function TrackShipment200ResponseFromJSON(json: any): TrackShipment200Response {
    return TrackShipment200ResponseFromJSONTyped(json, false);
}

export function TrackShipment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackShipment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'trackingNumber': json['trackingNumber'],
        'trackingUrl': json['trackingUrl'],
        'currentStatus': json['currentStatus'],
        'estimatedDelivery': json['estimatedDelivery'] === undefined ? undefined : json['estimatedDelivery'] === null ? null : json['estimatedDelivery'],
        'events': ((json['events'] as Array<any>).map(TrackShipment200ResponseEventsInnerFromJSON)),
    };
}

export function TrackShipment200ResponseToJSON(json: any): TrackShipment200Response {
    return TrackShipment200ResponseToJSONTyped(json, false);
}

export function TrackShipment200ResponseToJSONTyped(value?: TrackShipment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackingNumber': value['trackingNumber'],
        'trackingUrl': value['trackingUrl'],
        'currentStatus': value['currentStatus'],
        'estimatedDelivery': value['estimatedDelivery'],
        'events': ((value['events'] as Array<any>).map(TrackShipment200ResponseEventsInnerToJSON)),
    };
}

