/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrgWebhookRequest
 */
export interface UpdateOrgWebhookRequest {
    /**
     * Human-readable webhook name
     * @type {string}
     * @memberof UpdateOrgWebhookRequest
     */
    name?: string;
    /**
     * Webhook endpoint URL
     * @type {string}
     * @memberof UpdateOrgWebhookRequest
     */
    url?: string;
    /**
     * Events to subscribe to
     * @type {Array<UpdateOrgWebhookRequestEventsEnum>}
     * @memberof UpdateOrgWebhookRequest
     */
    events?: Array<UpdateOrgWebhookRequestEventsEnum>;
    /**
     * Whether the webhook is active
     * @type {boolean}
     * @memberof UpdateOrgWebhookRequest
     */
    isActive?: boolean;
}


/**
 * @export
 */
export const UpdateOrgWebhookRequestEventsEnum = {
    ShipmentCreated: 'shipment.created',
    ShipmentUpdated: 'shipment.updated',
    ShipmentDispatched: 'shipment.dispatched',
    ShipmentCancelled: 'shipment.cancelled',
    ShipmentError: 'shipment.error',
    OrderCreated: 'order.created',
    OrderUpdated: 'order.updated',
    OrderCancelled: 'order.cancelled',
    TrackingUpdated: 'tracking.updated'
} as const;
export type UpdateOrgWebhookRequestEventsEnum = typeof UpdateOrgWebhookRequestEventsEnum[keyof typeof UpdateOrgWebhookRequestEventsEnum];


/**
 * Check if a given object implements the UpdateOrgWebhookRequest interface.
 */
export function instanceOfUpdateOrgWebhookRequest(value: object): value is UpdateOrgWebhookRequest {
    return true;
}

export function UpdateOrgWebhookRequestFromJSON(json: any): UpdateOrgWebhookRequest {
    return UpdateOrgWebhookRequestFromJSONTyped(json, false);
}

export function UpdateOrgWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrgWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'events': json['events'] == null ? undefined : json['events'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function UpdateOrgWebhookRequestToJSON(json: any): UpdateOrgWebhookRequest {
    return UpdateOrgWebhookRequestToJSONTyped(json, false);
}

export function UpdateOrgWebhookRequestToJSONTyped(value?: UpdateOrgWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'events': value['events'],
        'isActive': value['isActive'],
    };
}

