/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.  Brands themselves are managed under the **Brands** tag. Retiring a brand is done with `POST /orgs/{orgId}/brands/{brandId}/archive` — permanent deletion is a dashboard-only action, since it is refused while any order, shipment, member or token still references the brand. Brands require a plan that includes them; creating one beyond your plan\'s limit returns `403`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrgBrandingRequest
 */
export interface UpdateOrgBrandingRequest {
    /**
     * Primary brand color (hex) — tints the document title and table headers
     * @type {string}
     * @memberof UpdateOrgBrandingRequest
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (hex) — tints the subtitle, section headings, and totals accent
     * @type {string}
     * @memberof UpdateOrgBrandingRequest
     */
    secondaryColor?: string | null;
}

/**
 * Check if a given object implements the UpdateOrgBrandingRequest interface.
 */
export function instanceOfUpdateOrgBrandingRequest(value: object): value is UpdateOrgBrandingRequest {
    return true;
}

export function UpdateOrgBrandingRequestFromJSON(json: any): UpdateOrgBrandingRequest {
    return UpdateOrgBrandingRequestFromJSONTyped(json, false);
}

export function UpdateOrgBrandingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrgBrandingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryColor': json['primaryColor'] === undefined ? undefined : json['primaryColor'] === null ? null : json['primaryColor'],
        'secondaryColor': json['secondaryColor'] === undefined ? undefined : json['secondaryColor'] === null ? null : json['secondaryColor'],
    };
}

export function UpdateOrgBrandingRequestToJSON(json: any): UpdateOrgBrandingRequest {
    return UpdateOrgBrandingRequestToJSONTyped(json, false);
}

export function UpdateOrgBrandingRequestToJSONTyped(value?: UpdateOrgBrandingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primaryColor': value['primaryColor'],
        'secondaryColor': value['secondaryColor'],
    };
}

