/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrgBrandingRequest
 */
export interface UpdateOrgBrandingRequest {
    /**
     * Primary brand color (hex) — tints the document title and table headers
     * @type {string}
     * @memberof UpdateOrgBrandingRequest
     */
    primaryColor?: string | null;
    /**
     * Secondary brand color (hex) — tints the subtitle, section headings, and totals accent
     * @type {string}
     * @memberof UpdateOrgBrandingRequest
     */
    secondaryColor?: string | null;
}

/**
 * Check if a given object implements the UpdateOrgBrandingRequest interface.
 */
export function instanceOfUpdateOrgBrandingRequest(value: object): value is UpdateOrgBrandingRequest {
    return true;
}

export function UpdateOrgBrandingRequestFromJSON(json: any): UpdateOrgBrandingRequest {
    return UpdateOrgBrandingRequestFromJSONTyped(json, false);
}

export function UpdateOrgBrandingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrgBrandingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryColor': json['primaryColor'] === undefined ? undefined : json['primaryColor'] === null ? null : json['primaryColor'],
        'secondaryColor': json['secondaryColor'] === undefined ? undefined : json['secondaryColor'] === null ? null : json['secondaryColor'],
    };
}

export function UpdateOrgBrandingRequestToJSON(json: any): UpdateOrgBrandingRequest {
    return UpdateOrgBrandingRequestToJSONTyped(json, false);
}

export function UpdateOrgBrandingRequestToJSONTyped(value?: UpdateOrgBrandingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'primaryColor': value['primaryColor'],
        'secondaryColor': value['secondaryColor'],
    };
}

