/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateShipmentRequestPickupDetails } from './CreateShipmentRequestPickupDetails';
import {
    CreateShipmentRequestPickupDetailsFromJSON,
    CreateShipmentRequestPickupDetailsFromJSONTyped,
    CreateShipmentRequestPickupDetailsToJSON,
    CreateShipmentRequestPickupDetailsToJSONTyped,
} from './CreateShipmentRequestPickupDetails';
import type { CreateShipmentRequestCarrierSettings } from './CreateShipmentRequestCarrierSettings';
import {
    CreateShipmentRequestCarrierSettingsFromJSON,
    CreateShipmentRequestCarrierSettingsFromJSONTyped,
    CreateShipmentRequestCarrierSettingsToJSON,
    CreateShipmentRequestCarrierSettingsToJSONTyped,
} from './CreateShipmentRequestCarrierSettings';
import type { CreateShipmentRequestPartiesInner } from './CreateShipmentRequestPartiesInner';
import {
    CreateShipmentRequestPartiesInnerFromJSON,
    CreateShipmentRequestPartiesInnerFromJSONTyped,
    CreateShipmentRequestPartiesInnerToJSON,
    CreateShipmentRequestPartiesInnerToJSONTyped,
} from './CreateShipmentRequestPartiesInner';
import type { CreateShipmentRequestParcelsInner } from './CreateShipmentRequestParcelsInner';
import {
    CreateShipmentRequestParcelsInnerFromJSON,
    CreateShipmentRequestParcelsInnerFromJSONTyped,
    CreateShipmentRequestParcelsInnerToJSON,
    CreateShipmentRequestParcelsInnerToJSONTyped,
} from './CreateShipmentRequestParcelsInner';

/**
 * 
 * @export
 * @interface UpdateShipmentRequest
 */
export interface UpdateShipmentRequest {
    /**
     * Customer-facing shipment reference.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    reference?: string;
    /**
     * Sender address identifier.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    addressId?: string | null;
    /**
     * Selected carrier service point identifier.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    servicePointId?: string | null;
    /**
     * Parties involved in the shipment. Optional when orderId is provided.
     * @type {Array<CreateShipmentRequestPartiesInner>}
     * @memberof UpdateShipmentRequest
     */
    parties?: Array<CreateShipmentRequestPartiesInner>;
    /**
     * Direction of the shipment relative to the organization.
     * @type {UpdateShipmentRequestTypeEnum}
     * @memberof UpdateShipmentRequest
     */
    type?: UpdateShipmentRequestTypeEnum;
    /**
     * 
     * @type {CreateShipmentRequestCarrierSettings}
     * @memberof UpdateShipmentRequest
     */
    carrierSettings?: CreateShipmentRequestCarrierSettings;
    /**
     * Parcels to include. Optional when orderId is provided.
     * @type {Array<CreateShipmentRequestParcelsInner>}
     * @memberof UpdateShipmentRequest
     */
    parcels?: Array<CreateShipmentRequestParcelsInner>;
    /**
     * 
     * @type {CreateShipmentRequestPickupDetails}
     * @memberof UpdateShipmentRequest
     */
    pickupDetails?: CreateShipmentRequestPickupDetails | null;
    /**
     * Incoterm governing the shipment.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    termOfTrade?: string;
    /**
     * Lifecycle status of the shipment.
     * @type {UpdateShipmentRequestStatusEnum}
     * @memberof UpdateShipmentRequest
     */
    status?: UpdateShipmentRequestStatusEnum;
    /**
     * Order to derive parties and parcels from.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    orderId?: string | null;
    /**
     * Printer to assign for labels.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    labelPrinterId?: string | null;
    /**
     * Printer to assign for documents.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    documentPrinterId?: string | null;
    /**
     * Shipping rule to apply to the shipment. Pass null to clear.
     * @type {string}
     * @memberof UpdateShipmentRequest
     */
    shippingRuleId?: string | null;
}


/**
 * @export
 */
export const UpdateShipmentRequestTypeEnum = {
    Outbound: 'outbound',
    Inbound: 'inbound'
} as const;
export type UpdateShipmentRequestTypeEnum = typeof UpdateShipmentRequestTypeEnum[keyof typeof UpdateShipmentRequestTypeEnum];

/**
 * @export
 */
export const UpdateShipmentRequestStatusEnum = {
    Draft: 'draft',
    Pending: 'pending',
    Processing: 'processing',
    Dispatched: 'dispatched',
    PartlyDispatched: 'partly_dispatched',
    Error: 'error',
    Cancelled: 'cancelled',
    OnHold: 'on_hold'
} as const;
export type UpdateShipmentRequestStatusEnum = typeof UpdateShipmentRequestStatusEnum[keyof typeof UpdateShipmentRequestStatusEnum];


/**
 * Check if a given object implements the UpdateShipmentRequest interface.
 */
export function instanceOfUpdateShipmentRequest(value: object): value is UpdateShipmentRequest {
    return true;
}

export function UpdateShipmentRequestFromJSON(json: any): UpdateShipmentRequest {
    return UpdateShipmentRequestFromJSONTyped(json, false);
}

export function UpdateShipmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateShipmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reference': json['reference'] == null ? undefined : json['reference'],
        'addressId': json['addressId'] === undefined ? undefined : json['addressId'] === null ? null : json['addressId'],
        'servicePointId': json['servicePointId'] === undefined ? undefined : json['servicePointId'] === null ? null : json['servicePointId'],
        'parties': json['parties'] == null ? undefined : ((json['parties'] as Array<any>).map(CreateShipmentRequestPartiesInnerFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
        'carrierSettings': json['carrierSettings'] == null ? undefined : CreateShipmentRequestCarrierSettingsFromJSON(json['carrierSettings']),
        'parcels': json['parcels'] == null ? undefined : ((json['parcels'] as Array<any>).map(CreateShipmentRequestParcelsInnerFromJSON)),
        'pickupDetails': json['pickupDetails'] === undefined ? undefined : json['pickupDetails'] === null ? null : CreateShipmentRequestPickupDetailsFromJSON(json['pickupDetails']),
        'termOfTrade': json['termOfTrade'] == null ? undefined : json['termOfTrade'],
        'status': json['status'] == null ? undefined : json['status'],
        'orderId': json['orderId'] === undefined ? undefined : json['orderId'] === null ? null : json['orderId'],
        'labelPrinterId': json['labelPrinterId'] === undefined ? undefined : json['labelPrinterId'] === null ? null : json['labelPrinterId'],
        'documentPrinterId': json['documentPrinterId'] === undefined ? undefined : json['documentPrinterId'] === null ? null : json['documentPrinterId'],
        'shippingRuleId': json['shippingRuleId'] === undefined ? undefined : json['shippingRuleId'] === null ? null : json['shippingRuleId'],
    };
}

export function UpdateShipmentRequestToJSON(json: any): UpdateShipmentRequest {
    return UpdateShipmentRequestToJSONTyped(json, false);
}

export function UpdateShipmentRequestToJSONTyped(value?: UpdateShipmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reference': value['reference'],
        'addressId': value['addressId'],
        'servicePointId': value['servicePointId'],
        'parties': value['parties'] == null ? undefined : ((value['parties'] as Array<any>).map(CreateShipmentRequestPartiesInnerToJSON)),
        'type': value['type'],
        'carrierSettings': CreateShipmentRequestCarrierSettingsToJSON(value['carrierSettings']),
        'parcels': value['parcels'] == null ? undefined : ((value['parcels'] as Array<any>).map(CreateShipmentRequestParcelsInnerToJSON)),
        'pickupDetails': CreateShipmentRequestPickupDetailsToJSON(value['pickupDetails']),
        'termOfTrade': value['termOfTrade'],
        'status': value['status'],
        'orderId': value['orderId'],
        'labelPrinterId': value['labelPrinterId'],
        'documentPrinterId': value['documentPrinterId'],
        'shippingRuleId': value['shippingRuleId'],
    };
}

