/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListCarriers200ResponseDataInnerConfigValue } from './ListCarriers200ResponseDataInnerConfigValue';
import {
    ListCarriers200ResponseDataInnerConfigValueFromJSON,
    ListCarriers200ResponseDataInnerConfigValueFromJSONTyped,
    ListCarriers200ResponseDataInnerConfigValueToJSON,
    ListCarriers200ResponseDataInnerConfigValueToJSONTyped,
} from './ListCarriers200ResponseDataInnerConfigValue';

/**
 * 
 * @export
 * @interface UpdateCarrierRequest
 */
export interface UpdateCarrierRequest {
    /**
     * Carrier display name
     * @type {string}
     * @memberof UpdateCarrierRequest
     */
    name?: string;
    /**
     * Carrier slug identifier
     * @type {string}
     * @memberof UpdateCarrierRequest
     */
    carrierSlug?: string;
    /**
     * Carrier configuration (required and optional fields)
     * @type {{ [key: string]: ListCarriers200ResponseDataInnerConfigValue; }}
     * @memberof UpdateCarrierRequest
     */
    config?: { [key: string]: ListCarriers200ResponseDataInnerConfigValue; };
}

/**
 * Check if a given object implements the UpdateCarrierRequest interface.
 */
export function instanceOfUpdateCarrierRequest(value: object): value is UpdateCarrierRequest {
    return true;
}

export function UpdateCarrierRequestFromJSON(json: any): UpdateCarrierRequest {
    return UpdateCarrierRequestFromJSONTyped(json, false);
}

export function UpdateCarrierRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCarrierRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'carrierSlug': json['carrierSlug'] == null ? undefined : json['carrierSlug'],
        'config': json['config'] == null ? undefined : (mapValues(json['config'], ListCarriers200ResponseDataInnerConfigValueFromJSON)),
    };
}

export function UpdateCarrierRequestToJSON(json: any): UpdateCarrierRequest {
    return UpdateCarrierRequestToJSONTyped(json, false);
}

export function UpdateCarrierRequestToJSONTyped(value?: UpdateCarrierRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'carrierSlug': value['carrierSlug'],
        'config': value['config'] == null ? undefined : (mapValues(value['config'], ListCarriers200ResponseDataInnerConfigValueToJSON)),
    };
}

