/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyApiTokenRequest
 */
export interface VerifyApiTokenRequest {
    /**
     * The API token to verify
     * @type {string}
     * @memberof VerifyApiTokenRequest
     */
    token: string;
}

/**
 * Check if a given object implements the VerifyApiTokenRequest interface.
 */
export function instanceOfVerifyApiTokenRequest(value: object): value is VerifyApiTokenRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function VerifyApiTokenRequestFromJSON(json: any): VerifyApiTokenRequest {
    return VerifyApiTokenRequestFromJSONTyped(json, false);
}

export function VerifyApiTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyApiTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function VerifyApiTokenRequestToJSON(json: any): VerifyApiTokenRequest {
    return VerifyApiTokenRequestToJSONTyped(json, false);
}

export function VerifyApiTokenRequestToJSONTyped(value?: VerifyApiTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

