/* tslint:disable */
/* eslint-disable */
/**
 * Zippendo Public API
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand\'s team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand\'s id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyApiToken200Response
 */
export interface VerifyApiToken200Response {
    /**
     * Whether the token is valid
     * @type {boolean}
     * @memberof VerifyApiToken200Response
     */
    valid: boolean;
    /**
     * Token identifier
     * @type {string}
     * @memberof VerifyApiToken200Response
     */
    tokenId?: string;
    /**
     * User identifier the token belongs to
     * @type {string}
     * @memberof VerifyApiToken200Response
     */
    userId?: string;
    /**
     * Organization identifier the token belongs to
     * @type {string}
     * @memberof VerifyApiToken200Response
     */
    orgId?: string;
    /**
     * Permission scopes granted by the token
     * @type {Array<string>}
     * @memberof VerifyApiToken200Response
     */
    scopes?: Array<string>;
    /**
     * Expiry timestamp (ISO 8601), null if it never expires
     * @type {string}
     * @memberof VerifyApiToken200Response
     */
    expiresAt?: string | null;
}

/**
 * Check if a given object implements the VerifyApiToken200Response interface.
 */
export function instanceOfVerifyApiToken200Response(value: object): value is VerifyApiToken200Response {
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function VerifyApiToken200ResponseFromJSON(json: any): VerifyApiToken200Response {
    return VerifyApiToken200ResponseFromJSONTyped(json, false);
}

export function VerifyApiToken200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyApiToken200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'],
        'tokenId': json['tokenId'] == null ? undefined : json['tokenId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : json['expiresAt'],
    };
}

export function VerifyApiToken200ResponseToJSON(json: any): VerifyApiToken200Response {
    return VerifyApiToken200ResponseToJSONTyped(json, false);
}

export function VerifyApiToken200ResponseToJSONTyped(value?: VerifyApiToken200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'tokenId': value['tokenId'],
        'userId': value['userId'],
        'orgId': value['orgId'],
        'scopes': value['scopes'],
        'expiresAt': value['expiresAt'],
    };
}

